





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics.CodeAnalysis;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Maps;
using Jabberwocky.Glass.Factory;
using Jabberwocky.Glass.Factory.Attributes;
using Jabberwocky.Glass.Models;
using System;   
using System.Collections.Generic;   
using System.Collections.Specialized;
using System.Linq;
using System.Text;
using Sitecore.Globalization;
using Sitecore.Data;
using Informa.Models.InterfaceFactory;
using Sitecore.Data;


namespace Informa.Models.FieldSources
{
  
 
  public class FactoryInterfaceDataSource : Sitecore.Buckets.FieldTypes.IDataSource
  {
      public Sitecore.Data.Items.Item[] ListQuery(Sitecore.Data.Items.Item item)
      {
          item.Fields.ReadAll();

          return item.Fields.Select(x => x.InnerItem).ToArray();

          //List<TemplateItem> templates = new List<TemplateItem>();
          //var template = item.Template;
          //if (template != null)
          //{
          //    if (template.ID == new ID("f4dbbc93-2591-4aa8-b71a-1dc4acd5c941"))
          //    {
          //        templates.Add(template);
          //    }

          //    foreach (var t in template.BaseTemplates) 

          //}

          //    return item.Parent.Children.ToArray();

      }
}
}
				  namespace Informa.Models.InterfaceFactory
{
  
 /// <summary>
	/// IInterfaceTemplate Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Velir/FactoryInterface/InterfaceTemplate</para>	
	/// <para>ID: f4dbbc93-2591-4aa8-b71a-1dc4acd5c941</para>	
	/// </summary>
	[GlassFactoryInterface]
	public partial interface IInterfaceFactoryTemplate 
	{
				}
				} 
namespace Informa.Models.Glass.Models.sitecore.templates.Velir.FactoryInterface
{


 	/// <summary>
	/// IListable Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Velir/FactoryInterface/Listable</para>	
	/// <para>ID: a3ec5da5-c37c-44a5-83f3-96d45b53389f</para>	
	/// </summary>
	[GlassFactoryInterface]
	public partial interface IListable : IInterfaceFactoryTemplate , global::Informa.Models.Glass.Models.sitecore.templates.Velir.FactoryInterface.IInterfaceTemplate
	{
								/// <summary>
					/// The ListableAuthor field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: 5f51fa66-5326-4aa6-9671-57a48aedeaa4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					
					Guid ListableAuthor  {get;}
								/// <summary>
					/// The ListableDate field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: 73f216e4-c244-4a3b-95ee-07d9ffd2d4f7</para>
					/// <para>Custom Data: </para>
					/// </summary>
					
					Guid ListableDate  {get;}
								/// <summary>
					/// The ListableImage field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: 6d481d3a-7c71-488f-88ff-9c53de9b4ac3</para>
					/// <para>Custom Data: </para>
					/// </summary>
					
					Guid ListableImage  {get;}
								/// <summary>
					/// The ListableTitle field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: a92e4bfb-3010-4332-a7a0-c788348993ce</para>
					/// <para>Custom Data: </para>
					/// </summary>
					
					Guid ListableTitle  {get;}
								/// <summary>
					/// The ListableTopics field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: 629bddb3-5e8e-49bb-a323-6e1c46bc7cb5</para>
					/// <para>Custom Data: </para>
					/// </summary>
					
					Guid ListableTopics  {get;}
								/// <summary>
					/// The ListableUrl field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: 5083ca52-6de6-4be9-a1e6-30e9579e782d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					
					Guid ListableUrl  {get;}
				}
						 
	public partial class ListableModel : IListable{

								/// <summary>
					/// The ListableAuthor field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: 5f51fa66-5326-4aa6-9671-57a48aedeaa4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					
					public virtual Guid ListableAuthor  {get; set;}
								/// <summary>
					/// The ListableDate field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: 73f216e4-c244-4a3b-95ee-07d9ffd2d4f7</para>
					/// <para>Custom Data: </para>
					/// </summary>
					
					public virtual Guid ListableDate  {get; set;}
								/// <summary>
					/// The ListableImage field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: 6d481d3a-7c71-488f-88ff-9c53de9b4ac3</para>
					/// <para>Custom Data: </para>
					/// </summary>
					
					public virtual Guid ListableImage  {get; set;}
								/// <summary>
					/// The ListableTitle field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: a92e4bfb-3010-4332-a7a0-c788348993ce</para>
					/// <para>Custom Data: </para>
					/// </summary>
					
					public virtual Guid ListableTitle  {get; set;}
								/// <summary>
					/// The ListableTopics field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: 629bddb3-5e8e-49bb-a323-6e1c46bc7cb5</para>
					/// <para>Custom Data: </para>
					/// </summary>
					
					public virtual Guid ListableTopics  {get; set;}
								/// <summary>
					/// The ListableUrl field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: 5083ca52-6de6-4be9-a1e6-30e9579e782d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					
					public virtual Guid ListableUrl  {get; set;}
						
	}

	public class ListableConfig : SitecoreGlassMap<ListableModel> 
    {
        public override void Configure()
        {
            Map(
                x => x.AutoMap()
				,
				x =>  x.Delegate(y =>  y.ListableAuthor).GetValue((context) => context.Item[context.Item.Fields["ListableAuthor"]?.Value])							                
				,
				x =>  x.Delegate(y =>  y.ListableDate).GetValue((context) => context.Item[context.Item.Fields["ListableDate"]?.Value])							                
				,
				x =>  x.Delegate(y =>  y.ListableImage).GetValue((context) => context.Item[context.Item.Fields["ListableImage"]?.Value])							                
				,
				x =>  x.Delegate(y =>  y.ListableTitle).GetValue((context) => context.Item[context.Item.Fields["ListableTitle"]?.Value])							                
				,
				x =>  x.Delegate(y =>  y.ListableTopics).GetValue((context) => context.Item[context.Item.Fields["ListableTopics"]?.Value])							                
				,
				x =>  x.Delegate(y =>  y.ListableUrl).GetValue((context) => context.Item[context.Item.Fields["ListableUrl"]?.Value])							                
				                );
        }
    }

}
namespace Informa.Models.Glass.Models.sitecore.templates.Velir.FactoryInterface
{


 	/// <summary>
	/// IInterfaceTemplate Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Velir/FactoryInterface/InterfaceTemplate</para>	
	/// <para>ID: f4dbbc93-2591-4aa8-b71a-1dc4acd5c941</para>	
	/// </summary>
	[GlassFactoryInterface]
	public partial interface IInterfaceTemplate : IInterfaceFactoryTemplate 
	{
				}
						 
	public partial class InterfaceTemplateModel : IInterfaceTemplate{

						
	}

	public class InterfaceTemplateConfig : SitecoreGlassMap<InterfaceTemplateModel> 
    {
        public override void Configure()
        {
            Map(
                x => x.AutoMap()
				                );
        }
    }

}
