





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics.CodeAnalysis;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Maps;
using Jabberwocky.Glass.Factory;
using Jabberwocky.Glass.Factory.Attributes;
using Jabberwocky.Glass.Models;
using System;   
using System.Collections.Generic;   
using System.Collections.Specialized;
using System.Linq;
using System.Text;
using Sitecore.Globalization;
using Sitecore.Data;
using Informa.Models.InterfaceFactory;
using Glass.Mapper.Sc.Fields;
using Sitecore.Data;


namespace Informa.Models.FieldSources
{
  
 
  public class FactoryInterfaceDataSource : Sitecore.Buckets.FieldTypes.IDataSource
  {
      public Sitecore.Data.Items.Item[] ListQuery(Sitecore.Data.Items.Item item)
      {
          item.Fields.ReadAll();

          return item.Fields.Select(x => x.InnerItem).ToArray();

          //List<TemplateItem> templates = new List<TemplateItem>();
          //var template = item.Template;
          //if (template != null)
          //{
          //    if (template.ID == new ID("f4dbbc93-2591-4aa8-b71a-1dc4acd5c941"))
          //    {
          //        templates.Add(template);
          //    }

          //    foreach (var t in template.BaseTemplates) 

          //}

          //    return item.Parent.Children.ToArray();

      }
}
}
				  namespace Informa.Models.InterfaceFactory
{
  
 /// <summary>
	/// IInterfaceTemplate Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Velir/FactoryInterface/InterfaceTemplate</para>	
	/// <para>ID: f4dbbc93-2591-4aa8-b71a-1dc4acd5c941</para>	
	/// </summary>
	[GlassFactoryInterface]
	public partial interface IInterfaceFactoryTemplate 
	{
				}
				} 
namespace Informa.Models.Glass.Models.sitecore.templates.Velir.FactoryInterface
{


 	/// <summary>
	/// ILinkable Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Velir/FactoryInterface/Linkable</para>	
	/// <para>ID: 3efeaf26-8572-417d-a8a8-6cb3a28eaf82</para>	
	/// </summary>
	[GlassFactoryInterface]
	public partial interface ILinkable : IInterfaceFactoryTemplate , global::Informa.Models.Glass.Models.sitecore.templates.Velir.FactoryInterface.IInterfaceTemplate
	{
	 Guid _Id { get; }
								/// <summary>
					/// The LinkableText field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 529c867f-2816-43a9-964a-3f16c014a4f7</para>
					/// <para>Custom Data: type=string</para>
					/// </summary>
					
					string LinkableTexts  {get;}
								/// <summary>
					/// The LinkableUrl field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: d156cd07-71a4-4daa-b52a-5ce602d6d3bb</para>
					/// <para>Custom Data: type=Link</para>
					/// </summary>
					
					Link LinkableUrls  {get;}
				}
						 
	public partial class LinkableModel : ILinkable{

	  [SitecoreId]
    public Guid _Id { get; set; }
								/// <summary>
					/// The LinkableText field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 529c867f-2816-43a9-964a-3f16c014a4f7</para>
					/// <para>Custom Data: type=string</para>
					/// </summary>
					
					public virtual string LinkableTexts  {get; set;}
								/// <summary>
					/// The LinkableUrl field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: d156cd07-71a4-4daa-b52a-5ce602d6d3bb</para>
					/// <para>Custom Data: type=Link</para>
					/// </summary>
					
					public virtual Link LinkableUrls  {get; set;}
						
	}

	public class LinkableConfig : SitecoreGlassMap<LinkableModel> 
    {
        public override void Configure()
        {
            Map(
                x => x.AutoMap()
				,
				x =>  x.Delegate(y =>  y.LinkableTexts).GetValue((context) => 
				{
					if(!string.IsNullOrEmpty(context.Item.Fields["LinkableTexts"].Value)){
						return context.Item[context.Item.Fields["LinkableTexts"]?.Value];
					}					                

					return null;
				})
				,
				x =>  x.Delegate(y =>  y.LinkableUrls).GetValue((context) => 
				{
					if(!string.IsNullOrEmpty(context.Item.Fields["LinkableUrls"].Value)){
						return context.Item[context.Item.Fields["LinkableUrls"]?.Value];
					}					                

					return null;
				})
				                );
        }
    }

}
namespace Informa.Models.Glass.Models.sitecore.templates.Velir.FactoryInterface
{


 	/// <summary>
	/// IListable Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Velir/FactoryInterface/Listable</para>	
	/// <para>ID: a3ec5da5-c37c-44a5-83f3-96d45b53389f</para>	
	/// </summary>
	[GlassFactoryInterface]
	public partial interface IListable : IInterfaceFactoryTemplate , global::Informa.Models.Glass.Models.sitecore.templates.Velir.FactoryInterface.IInterfaceTemplate
	{
	 Guid _Id { get; }
								/// <summary>
					/// The ListableAuthors field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 5f51fa66-5326-4aa6-9671-57a48aedeaa4</para>
					/// <para>Custom Data: generic=ILinkable</para>
					/// </summary>
					
					IEnumerable<ILinkable> ListableAuthors  {get;}
								/// <summary>
					/// The ListableDate field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 73f216e4-c244-4a3b-95ee-07d9ffd2d4f7</para>
					/// <para>Custom Data: type=DateTime?</para>
					/// </summary>
					
					DateTime? ListableDates  {get;}
								/// <summary>
					/// The ListableImage field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 6d481d3a-7c71-488f-88ff-9c53de9b4ac3</para>
					/// <para>Custom Data: type=Image</para>
					/// </summary>
					
					Image ListableImages  {get;}
								/// <summary>
					/// The ListableSummary field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 241b01c9-b518-4182-9b94-c40db3fb9cb2</para>
					/// <para>Custom Data: type=string</para>
					/// </summary>
					
					string ListableSummaries  {get;}
								/// <summary>
					/// The ListableTitle field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: a92e4bfb-3010-4332-a7a0-c788348993ce</para>
					/// <para>Custom Data: type=string</para>
					/// </summary>
					
					string ListableTitles  {get;}
								/// <summary>
					/// The ListableTopics field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 629bddb3-5e8e-49bb-a323-6e1c46bc7cb5</para>
					/// <para>Custom Data: generic=ILinkable</para>
					/// </summary>
					
					IEnumerable<ILinkable> ListableTopics  {get;}
								/// <summary>
					/// The ListableUrl field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 5083ca52-6de6-4be9-a1e6-30e9579e782d</para>
					/// <para>Custom Data: type=Link</para>
					/// </summary>
					
					Link ListableUrls  {get;}
				}
						 
	public partial class ListableModel : IListable{

	  [SitecoreId]
    public Guid _Id { get; set; }
								/// <summary>
					/// The ListableAuthors field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 5f51fa66-5326-4aa6-9671-57a48aedeaa4</para>
					/// <para>Custom Data: generic=ILinkable</para>
					/// </summary>
					
					public virtual IEnumerable<ILinkable> ListableAuthors  {get; set;}
								/// <summary>
					/// The ListableDate field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 73f216e4-c244-4a3b-95ee-07d9ffd2d4f7</para>
					/// <para>Custom Data: type=DateTime?</para>
					/// </summary>
					
					public virtual DateTime? ListableDates  {get; set;}
								/// <summary>
					/// The ListableImage field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 6d481d3a-7c71-488f-88ff-9c53de9b4ac3</para>
					/// <para>Custom Data: type=Image</para>
					/// </summary>
					
					public virtual Image ListableImages  {get; set;}
								/// <summary>
					/// The ListableSummary field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 241b01c9-b518-4182-9b94-c40db3fb9cb2</para>
					/// <para>Custom Data: type=string</para>
					/// </summary>
					
					public virtual string ListableSummaries  {get; set;}
								/// <summary>
					/// The ListableTitle field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: a92e4bfb-3010-4332-a7a0-c788348993ce</para>
					/// <para>Custom Data: type=string</para>
					/// </summary>
					
					public virtual string ListableTitles  {get; set;}
								/// <summary>
					/// The ListableTopics field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 629bddb3-5e8e-49bb-a323-6e1c46bc7cb5</para>
					/// <para>Custom Data: generic=ILinkable</para>
					/// </summary>
					
					public virtual IEnumerable<ILinkable> ListableTopics  {get; set;}
								/// <summary>
					/// The ListableUrl field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 5083ca52-6de6-4be9-a1e6-30e9579e782d</para>
					/// <para>Custom Data: type=Link</para>
					/// </summary>
					
					public virtual Link ListableUrls  {get; set;}
						
	}

	public class ListableConfig : SitecoreGlassMap<ListableModel> 
    {
        public override void Configure()
        {
            Map(
                x => x.AutoMap()
				,
				x =>  x.Delegate(y =>  y.ListableAuthors).GetValue((context) => 
				{
					if(!string.IsNullOrEmpty(context.Item.Fields["ListableAuthors"].Value)){
						return context.Item[context.Item.Fields["ListableAuthors"]?.Value];
					}					                

					return null;
				})
				,
				x =>  x.Delegate(y =>  y.ListableDates).GetValue((context) => 
				{
					if(!string.IsNullOrEmpty(context.Item.Fields["ListableDates"].Value)){
						return context.Item[context.Item.Fields["ListableDates"]?.Value];
					}					                

					return null;
				})
				,
				x =>  x.Delegate(y =>  y.ListableImages).GetValue((context) => 
				{
					if(!string.IsNullOrEmpty(context.Item.Fields["ListableImages"].Value)){
						return context.Item[context.Item.Fields["ListableImages"]?.Value];
					}					                

					return null;
				})
				,
				x =>  x.Delegate(y =>  y.ListableSummaries).GetValue((context) => 
				{
					if(!string.IsNullOrEmpty(context.Item.Fields["ListableSummaries"].Value)){
						return context.Item[context.Item.Fields["ListableSummaries"]?.Value];
					}					                

					return null;
				})
				,
				x =>  x.Delegate(y =>  y.ListableTitles).GetValue((context) => 
				{
					if(!string.IsNullOrEmpty(context.Item.Fields["ListableTitles"].Value)){
						return context.Item[context.Item.Fields["ListableTitles"]?.Value];
					}					                

					return null;
				})
				,
				x =>  x.Delegate(y =>  y.ListableTopics).GetValue((context) => 
				{
					if(!string.IsNullOrEmpty(context.Item.Fields["ListableTopics"].Value)){
						return context.Item[context.Item.Fields["ListableTopics"]?.Value];
					}					                

					return null;
				})
				,
				x =>  x.Delegate(y =>  y.ListableUrls).GetValue((context) => 
				{
					if(!string.IsNullOrEmpty(context.Item.Fields["ListableUrls"].Value)){
						return context.Item[context.Item.Fields["ListableUrls"]?.Value];
					}					                

					return null;
				})
				                );
        }
    }

}
namespace Informa.Models.Glass.Models.sitecore.templates.Velir.FactoryInterface
{


 	/// <summary>
	/// IInterfaceTemplate Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Velir/FactoryInterface/InterfaceTemplate</para>	
	/// <para>ID: f4dbbc93-2591-4aa8-b71a-1dc4acd5c941</para>	
	/// </summary>
	[GlassFactoryInterface]
	public partial interface IInterfaceTemplate : IInterfaceFactoryTemplate 
	{
	 Guid _Id { get; }
				}
						 
	public partial class InterfaceTemplateModel : IInterfaceTemplate{

	  [SitecoreId]
    public Guid _Id { get; set; }
						
	}

	public class InterfaceTemplateConfig : SitecoreGlassMap<InterfaceTemplateModel> 
    {
        public override void Configure()
        {
            Map(
                x => x.AutoMap()
				                );
        }
    }

}
