





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Collections.Specialized;
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Jabberwocky.Glass.Models;
using Sitecore.Globalization;
using Sitecore.Data;



namespace Informa.Models.Informa.Models.sitecore.templates.User_Defined.Pages
{


 	/// <summary>
	/// IGeneral_Content_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pages/General Content Page</para>	
	/// <para>ID: 0933b8e2-67c4-4d83-a43d-a4c67b863f4d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IGeneral_Content_PageConstants.TemplateIdString)]
	public partial interface IGeneral_Content_Page : IGlassBase , global::Informa.Models.Informa.Models.sitecore.templates.User_Defined.Base_Templates.I___BasePage
	{
				}

	
		/// <summary>
		/// IGeneral_Content_Page Interface
		/// <para></para>
		/// <para>Path: /sitecore/templates/User Defined/Pages/General Content Page</para>	
		/// <para>ID: 0933b8e2-67c4-4d83-a43d-a4c67b863f4d</para>	
		/// </summary>
		[SitecoreType]
		public partial interface IGeneral_Content_Page__Raw : IGlassBase , global::Informa.Models.Informa.Models.sitecore.templates.User_Defined.Base_Templates.I___BasePage__Raw
		{
						}
	
	public static partial class IGeneral_Content_PageConstants{

			public const string TemplateIdString = "0933b8e2-67c4-4d83-a43d-a4c67b863f4d";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "General Content Page";

					
			public static readonly ID Custom_Meta_TagsFieldId = new ID("58c1bb46-882f-4f72-8e76-72fca199706b");
			public const string Custom_Meta_TagsFieldName = "Custom Meta Tags";

						
					
			public static readonly ID Meta_DescriptionFieldId = new ID("15f619cd-b981-477f-b496-b88577615c11");
			public const string Meta_DescriptionFieldName = "Meta Description";

						
					
			public static readonly ID Meta_KeywordsFieldId = new ID("77b76c9b-2c0e-44cb-aa78-5b9cb1b535ba");
			public const string Meta_KeywordsFieldName = "Meta Keywords";

						
					
			public static readonly ID Meta_Title_OverrideFieldId = new ID("31603f25-6d9c-4954-bcde-342e1e184a30");
			public const string Meta_Title_OverrideFieldName = "Meta Title Override";

						
					
			public static readonly ID Navigation_TitleFieldId = new ID("8f4ee718-6fa0-42a5-85c4-6c8fe8b1fcd4");
			public const string Navigation_TitleFieldName = "Navigation Title";

						
					
			public static readonly ID BodyFieldId = new ID("446a339b-e1d9-4de1-8b5e-db7942ef1723");
			public const string BodyFieldName = "Body";

							public static readonly ID Body__RawFieldId = new ID("446a339b-e1d9-4de1-8b5e-db7942ef1723");
				public const string Body__RawFieldName = "Body";
						
					
			public static readonly ID Sub_TitleFieldId = new ID("f1d1dc93-63df-4afa-b60f-b3a3e9d36675");
			public const string Sub_TitleFieldName = "Sub Title";

						
					
			public static readonly ID TitleFieldId = new ID("2d750eff-9058-4abf-a7ff-57ffe5da1e3c");
			public const string TitleFieldName = "Title";

						
			

	}

}
namespace Informa.Models.Informa.Models.sitecore.templates.User_Defined.Pages
{


 	/// <summary>
	/// IArticle Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pages/Article</para>	
	/// <para>ID: 11380b5d-3531-4570-b213-efc5312266e4</para>	
	/// </summary>
	[SitecoreType(TemplateId=IArticleConstants.TemplateIdString)]
	public partial interface IArticle : IGlassBase , global::Informa.Models.Informa.Models.sitecore.templates.User_Defined.Base_Templates.I___BasePage
	{
				}

	
		/// <summary>
		/// IArticle Interface
		/// <para></para>
		/// <para>Path: /sitecore/templates/User Defined/Pages/Article</para>	
		/// <para>ID: 11380b5d-3531-4570-b213-efc5312266e4</para>	
		/// </summary>
		[SitecoreType]
		public partial interface IArticle__Raw : IGlassBase , global::Informa.Models.Informa.Models.sitecore.templates.User_Defined.Base_Templates.I___BasePage__Raw
		{
						}
	
	public static partial class IArticleConstants{

			public const string TemplateIdString = "11380b5d-3531-4570-b213-efc5312266e4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Article";

					
			public static readonly ID Custom_Meta_TagsFieldId = new ID("58c1bb46-882f-4f72-8e76-72fca199706b");
			public const string Custom_Meta_TagsFieldName = "Custom Meta Tags";

						
					
			public static readonly ID Meta_DescriptionFieldId = new ID("15f619cd-b981-477f-b496-b88577615c11");
			public const string Meta_DescriptionFieldName = "Meta Description";

						
					
			public static readonly ID Meta_KeywordsFieldId = new ID("77b76c9b-2c0e-44cb-aa78-5b9cb1b535ba");
			public const string Meta_KeywordsFieldName = "Meta Keywords";

						
					
			public static readonly ID Meta_Title_OverrideFieldId = new ID("31603f25-6d9c-4954-bcde-342e1e184a30");
			public const string Meta_Title_OverrideFieldName = "Meta Title Override";

						
					
			public static readonly ID Navigation_TitleFieldId = new ID("8f4ee718-6fa0-42a5-85c4-6c8fe8b1fcd4");
			public const string Navigation_TitleFieldName = "Navigation Title";

						
					
			public static readonly ID BodyFieldId = new ID("446a339b-e1d9-4de1-8b5e-db7942ef1723");
			public const string BodyFieldName = "Body";

							public static readonly ID Body__RawFieldId = new ID("446a339b-e1d9-4de1-8b5e-db7942ef1723");
				public const string Body__RawFieldName = "Body";
						
					
			public static readonly ID Sub_TitleFieldId = new ID("f1d1dc93-63df-4afa-b60f-b3a3e9d36675");
			public const string Sub_TitleFieldName = "Sub Title";

						
					
			public static readonly ID TitleFieldId = new ID("2d750eff-9058-4abf-a7ff-57ffe5da1e3c");
			public const string TitleFieldName = "Title";

						
			

	}

}
namespace Informa.Models.Informa.Models.sitecore.templates.User_Defined.View_Templates
{


 	/// <summary>
	/// IAuthored_Content_List_Item_View Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/View Templates/Authored Content List Item View</para>	
	/// <para>ID: 1b4738c7-1fb1-4b24-a030-ac98171528a7</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAuthored_Content_List_Item_ViewConstants.TemplateIdString)]
	public partial interface IAuthored_Content_List_Item_View : IGlassBase 
	{
				}

	
		/// <summary>
		/// IAuthored_Content_List_Item_View Interface
		/// <para></para>
		/// <para>Path: /sitecore/templates/User Defined/View Templates/Authored Content List Item View</para>	
		/// <para>ID: 1b4738c7-1fb1-4b24-a030-ac98171528a7</para>	
		/// </summary>
		[SitecoreType]
		public partial interface IAuthored_Content_List_Item_View__Raw : IGlassBase 
		{
						}
	
	public static partial class IAuthored_Content_List_Item_ViewConstants{

			public const string TemplateIdString = "1b4738c7-1fb1-4b24-a030-ac98171528a7";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Authored Content List Item View";

			

	}

}
namespace Informa.Models.Informa.Models.sitecore.templates.User_Defined.Objects
{


 	/// <summary>
	/// ITaxonomy_Item Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Objects/Taxonomy Item</para>	
	/// <para>ID: 6d72d3c0-b5d7-4d08-9bdd-0d9627ef5ad1</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITaxonomy_ItemConstants.TemplateIdString)]
	public partial interface ITaxonomy_Item : IGlassBase 
	{
				}

	
		/// <summary>
		/// ITaxonomy_Item Interface
		/// <para></para>
		/// <para>Path: /sitecore/templates/User Defined/Objects/Taxonomy Item</para>	
		/// <para>ID: 6d72d3c0-b5d7-4d08-9bdd-0d9627ef5ad1</para>	
		/// </summary>
		[SitecoreType]
		public partial interface ITaxonomy_Item__Raw : IGlassBase 
		{
						}
	
	public static partial class ITaxonomy_ItemConstants{

			public const string TemplateIdString = "6d72d3c0-b5d7-4d08-9bdd-0d9627ef5ad1";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Taxonomy Item";

			

	}

}
namespace Informa.Models.Informa.Models.sitecore.templates.User_Defined.Pages
{


 	/// <summary>
	/// IHome_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pages/Home Page</para>	
	/// <para>ID: 88caca5d-2ae1-4739-8145-399f3486c2de</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHome_PageConstants.TemplateIdString)]
	public partial interface IHome_Page : IGlassBase , global::Informa.Models.Informa.Models.sitecore.templates.User_Defined.Base_Templates.I___BasePage
	{
				}

	
		/// <summary>
		/// IHome_Page Interface
		/// <para></para>
		/// <para>Path: /sitecore/templates/User Defined/Pages/Home Page</para>	
		/// <para>ID: 88caca5d-2ae1-4739-8145-399f3486c2de</para>	
		/// </summary>
		[SitecoreType]
		public partial interface IHome_Page__Raw : IGlassBase , global::Informa.Models.Informa.Models.sitecore.templates.User_Defined.Base_Templates.I___BasePage__Raw
		{
						}
	
	public static partial class IHome_PageConstants{

			public const string TemplateIdString = "88caca5d-2ae1-4739-8145-399f3486c2de";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Home Page";

					
			public static readonly ID Custom_Meta_TagsFieldId = new ID("58c1bb46-882f-4f72-8e76-72fca199706b");
			public const string Custom_Meta_TagsFieldName = "Custom Meta Tags";

						
					
			public static readonly ID Meta_DescriptionFieldId = new ID("15f619cd-b981-477f-b496-b88577615c11");
			public const string Meta_DescriptionFieldName = "Meta Description";

						
					
			public static readonly ID Meta_KeywordsFieldId = new ID("77b76c9b-2c0e-44cb-aa78-5b9cb1b535ba");
			public const string Meta_KeywordsFieldName = "Meta Keywords";

						
					
			public static readonly ID Meta_Title_OverrideFieldId = new ID("31603f25-6d9c-4954-bcde-342e1e184a30");
			public const string Meta_Title_OverrideFieldName = "Meta Title Override";

						
					
			public static readonly ID Navigation_TitleFieldId = new ID("8f4ee718-6fa0-42a5-85c4-6c8fe8b1fcd4");
			public const string Navigation_TitleFieldName = "Navigation Title";

						
					
			public static readonly ID BodyFieldId = new ID("446a339b-e1d9-4de1-8b5e-db7942ef1723");
			public const string BodyFieldName = "Body";

							public static readonly ID Body__RawFieldId = new ID("446a339b-e1d9-4de1-8b5e-db7942ef1723");
				public const string Body__RawFieldName = "Body";
						
					
			public static readonly ID Sub_TitleFieldId = new ID("f1d1dc93-63df-4afa-b60f-b3a3e9d36675");
			public const string Sub_TitleFieldName = "Sub Title";

						
					
			public static readonly ID TitleFieldId = new ID("2d750eff-9058-4abf-a7ff-57ffe5da1e3c");
			public const string TitleFieldName = "Title";

						
			

	}

}
namespace Informa.Models.Informa.Models.sitecore.templates.User_Defined.Base_Templates
{


 	/// <summary>
	/// I___BasePage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base Templates/__BasePage</para>	
	/// <para>ID: 8cb9b3dc-fb05-4f6c-a73b-19eadb3a6391</para>	
	/// </summary>
	[SitecoreType(TemplateId=I___BasePageConstants.TemplateIdString)]
	public partial interface I___BasePage : IGlassBase , global::Informa.Models.Informa.Models.sitecore.templates.User_Defined.Base_Templates.I___BaseItem
	{
								/// <summary>
					/// The Custom Meta Tags field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 58c1bb46-882f-4f72-8e76-72fca199706b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I___BasePageConstants.Custom_Meta_TagsFieldName, Setting = SitecoreFieldSettings.InferType)]
					string Custom_Meta_Tags  {get; set;}
								/// <summary>
					/// The Meta Description field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 15f619cd-b981-477f-b496-b88577615c11</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I___BasePageConstants.Meta_DescriptionFieldName, Setting = SitecoreFieldSettings.InferType)]
					string Meta_Description  {get; set;}
								/// <summary>
					/// The Meta Keywords field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 77b76c9b-2c0e-44cb-aa78-5b9cb1b535ba</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I___BasePageConstants.Meta_KeywordsFieldName, Setting = SitecoreFieldSettings.InferType)]
					string Meta_Keywords  {get; set;}
								/// <summary>
					/// The Meta Title Override field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 31603f25-6d9c-4954-bcde-342e1e184a30</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I___BasePageConstants.Meta_Title_OverrideFieldName, Setting = SitecoreFieldSettings.InferType)]
					string Meta_Title_Override  {get; set;}
								/// <summary>
					/// The Navigation Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 8f4ee718-6fa0-42a5-85c4-6c8fe8b1fcd4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I___BasePageConstants.Navigation_TitleFieldName, Setting = SitecoreFieldSettings.InferType)]
					string Navigation_Title  {get; set;}
								/// <summary>
					/// The Body field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 446a339b-e1d9-4de1-8b5e-db7942ef1723</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I___BasePageConstants.BodyFieldName, Setting = SitecoreFieldSettings.InferType)]
					string Body  {get; set;}
								/// <summary>
					/// The Sub Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: f1d1dc93-63df-4afa-b60f-b3a3e9d36675</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I___BasePageConstants.Sub_TitleFieldName, Setting = SitecoreFieldSettings.InferType)]
					string Sub_Title  {get; set;}
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 2d750eff-9058-4abf-a7ff-57ffe5da1e3c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I___BasePageConstants.TitleFieldName, Setting = SitecoreFieldSettings.InferType)]
					string Title  {get; set;}
				}

	
		/// <summary>
		/// I___BasePage Interface
		/// <para></para>
		/// <para>Path: /sitecore/templates/User Defined/Base Templates/__BasePage</para>	
		/// <para>ID: 8cb9b3dc-fb05-4f6c-a73b-19eadb3a6391</para>	
		/// </summary>
		[SitecoreType]
		public partial interface I___BasePage__Raw : IGlassBase , global::Informa.Models.Informa.Models.sitecore.templates.User_Defined.Base_Templates.I___BaseItem__Raw
		{
										/// <summary>
						/// The Custom Meta Tags field.
						/// <para></para>
						/// <para>Field Type: Single-Line Text</para>		
						/// <para>Field ID: 58c1bb46-882f-4f72-8e76-72fca199706b</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(I___BasePageConstants.Custom_Meta_TagsFieldName, Setting = SitecoreFieldSettings.InferType)]
						string Custom_Meta_Tags  {get; set;}
										/// <summary>
						/// The Meta Description field.
						/// <para></para>
						/// <para>Field Type: Single-Line Text</para>		
						/// <para>Field ID: 15f619cd-b981-477f-b496-b88577615c11</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(I___BasePageConstants.Meta_DescriptionFieldName, Setting = SitecoreFieldSettings.InferType)]
						string Meta_Description  {get; set;}
										/// <summary>
						/// The Meta Keywords field.
						/// <para></para>
						/// <para>Field Type: Single-Line Text</para>		
						/// <para>Field ID: 77b76c9b-2c0e-44cb-aa78-5b9cb1b535ba</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(I___BasePageConstants.Meta_KeywordsFieldName, Setting = SitecoreFieldSettings.InferType)]
						string Meta_Keywords  {get; set;}
										/// <summary>
						/// The Meta Title Override field.
						/// <para></para>
						/// <para>Field Type: Single-Line Text</para>		
						/// <para>Field ID: 31603f25-6d9c-4954-bcde-342e1e184a30</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(I___BasePageConstants.Meta_Title_OverrideFieldName, Setting = SitecoreFieldSettings.InferType)]
						string Meta_Title_Override  {get; set;}
										/// <summary>
						/// The Navigation Title field.
						/// <para></para>
						/// <para>Field Type: Single-Line Text</para>		
						/// <para>Field ID: 8f4ee718-6fa0-42a5-85c4-6c8fe8b1fcd4</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(I___BasePageConstants.Navigation_TitleFieldName, Setting = SitecoreFieldSettings.InferType)]
						string Navigation_Title  {get; set;}
										/// <summary>
						/// The Body field.
						/// <para></para>
						/// <para>Field Type: Rich Text</para>		
						/// <para>Field ID: 446a339b-e1d9-4de1-8b5e-db7942ef1723</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(I___BasePageConstants.BodyFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
						string Body  {get; set;}
										/// <summary>
						/// The Sub Title field.
						/// <para></para>
						/// <para>Field Type: Single-Line Text</para>		
						/// <para>Field ID: f1d1dc93-63df-4afa-b60f-b3a3e9d36675</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(I___BasePageConstants.Sub_TitleFieldName, Setting = SitecoreFieldSettings.InferType)]
						string Sub_Title  {get; set;}
										/// <summary>
						/// The Title field.
						/// <para></para>
						/// <para>Field Type: Single-Line Text</para>		
						/// <para>Field ID: 2d750eff-9058-4abf-a7ff-57ffe5da1e3c</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(I___BasePageConstants.TitleFieldName, Setting = SitecoreFieldSettings.InferType)]
						string Title  {get; set;}
						}
	
	public static partial class I___BasePageConstants{

			public const string TemplateIdString = "8cb9b3dc-fb05-4f6c-a73b-19eadb3a6391";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "__BasePage";

					
			public static readonly ID Custom_Meta_TagsFieldId = new ID("58c1bb46-882f-4f72-8e76-72fca199706b");
			public const string Custom_Meta_TagsFieldName = "Custom Meta Tags";

						
					
			public static readonly ID Meta_DescriptionFieldId = new ID("15f619cd-b981-477f-b496-b88577615c11");
			public const string Meta_DescriptionFieldName = "Meta Description";

						
					
			public static readonly ID Meta_KeywordsFieldId = new ID("77b76c9b-2c0e-44cb-aa78-5b9cb1b535ba");
			public const string Meta_KeywordsFieldName = "Meta Keywords";

						
					
			public static readonly ID Meta_Title_OverrideFieldId = new ID("31603f25-6d9c-4954-bcde-342e1e184a30");
			public const string Meta_Title_OverrideFieldName = "Meta Title Override";

						
					
			public static readonly ID Navigation_TitleFieldId = new ID("8f4ee718-6fa0-42a5-85c4-6c8fe8b1fcd4");
			public const string Navigation_TitleFieldName = "Navigation Title";

						
					
			public static readonly ID BodyFieldId = new ID("446a339b-e1d9-4de1-8b5e-db7942ef1723");
			public const string BodyFieldName = "Body";

							public static readonly ID Body__RawFieldId = new ID("446a339b-e1d9-4de1-8b5e-db7942ef1723");
				public const string Body__RawFieldName = "Body";
						
					
			public static readonly ID Sub_TitleFieldId = new ID("f1d1dc93-63df-4afa-b60f-b3a3e9d36675");
			public const string Sub_TitleFieldName = "Sub Title";

						
					
			public static readonly ID TitleFieldId = new ID("2d750eff-9058-4abf-a7ff-57ffe5da1e3c");
			public const string TitleFieldName = "Title";

						
			

	}

}
namespace Informa.Models.Informa.Models.sitecore.templates.User_Defined.Configuration
{


 	/// <summary>
	/// ISite_Config Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Configuration/Site Config</para>	
	/// <para>ID: 997a3064-65f5-45cd-b32f-9ec61e90a610</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISite_ConfigConstants.TemplateIdString)]
	public partial interface ISite_Config : IGlassBase 
	{
				}

	
		/// <summary>
		/// ISite_Config Interface
		/// <para></para>
		/// <para>Path: /sitecore/templates/User Defined/Configuration/Site Config</para>	
		/// <para>ID: 997a3064-65f5-45cd-b32f-9ec61e90a610</para>	
		/// </summary>
		[SitecoreType]
		public partial interface ISite_Config__Raw : IGlassBase 
		{
						}
	
	public static partial class ISite_ConfigConstants{

			public const string TemplateIdString = "997a3064-65f5-45cd-b32f-9ec61e90a610";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Site Config";

			

	}

}
namespace Informa.Models.Informa.Models.sitecore.templates.User_Defined
{


 	/// <summary>
	/// IAuthored_Content Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Authored Content</para>	
	/// <para>ID: bc9061e8-27c6-4dd4-b342-50547e4a25cc</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAuthored_ContentConstants.TemplateIdString)]
	public partial interface IAuthored_Content : IGlassBase 
	{
								/// <summary>
					/// The Body field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 423ba8be-c356-44de-a608-361f09818330</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAuthored_ContentConstants.BodyFieldName, Setting = SitecoreFieldSettings.InferType)]
					string Body  {get; set;}
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: b820f81e-734a-4ef5-b35e-210b406aee13</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAuthored_ContentConstants.TitleFieldName, Setting = SitecoreFieldSettings.InferType)]
					string Title  {get; set;}
				}

	
		/// <summary>
		/// IAuthored_Content Interface
		/// <para></para>
		/// <para>Path: /sitecore/templates/User Defined/Authored Content</para>	
		/// <para>ID: bc9061e8-27c6-4dd4-b342-50547e4a25cc</para>	
		/// </summary>
		[SitecoreType]
		public partial interface IAuthored_Content__Raw : IGlassBase 
		{
										/// <summary>
						/// The Body field.
						/// <para></para>
						/// <para>Field Type: Rich Text</para>		
						/// <para>Field ID: 423ba8be-c356-44de-a608-361f09818330</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(IAuthored_ContentConstants.BodyFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
						string Body  {get; set;}
										/// <summary>
						/// The Title field.
						/// <para></para>
						/// <para>Field Type: Single-Line Text</para>		
						/// <para>Field ID: b820f81e-734a-4ef5-b35e-210b406aee13</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(IAuthored_ContentConstants.TitleFieldName, Setting = SitecoreFieldSettings.InferType)]
						string Title  {get; set;}
						}
	
	public static partial class IAuthored_ContentConstants{

			public const string TemplateIdString = "bc9061e8-27c6-4dd4-b342-50547e4a25cc";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Authored Content";

					
			public static readonly ID BodyFieldId = new ID("423ba8be-c356-44de-a608-361f09818330");
			public const string BodyFieldName = "Body";

							public static readonly ID Body__RawFieldId = new ID("423ba8be-c356-44de-a608-361f09818330");
				public const string Body__RawFieldName = "Body";
						
					
			public static readonly ID TitleFieldId = new ID("b820f81e-734a-4ef5-b35e-210b406aee13");
			public const string TitleFieldName = "Title";

						
			

	}

}
namespace Informa.Models.Informa.Models.sitecore.templates.User_Defined.Base_Templates
{


 	/// <summary>
	/// I___BaseItem Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base Templates/__BaseItem</para>	
	/// <para>ID: c3799c90-e42b-43c5-a0d0-ac3f924252fb</para>	
	/// </summary>
	[SitecoreType(TemplateId=I___BaseItemConstants.TemplateIdString)]
	public partial interface I___BaseItem : IGlassBase 
	{
				}

	
		/// <summary>
		/// I___BaseItem Interface
		/// <para></para>
		/// <para>Path: /sitecore/templates/User Defined/Base Templates/__BaseItem</para>	
		/// <para>ID: c3799c90-e42b-43c5-a0d0-ac3f924252fb</para>	
		/// </summary>
		[SitecoreType]
		public partial interface I___BaseItem__Raw : IGlassBase 
		{
						}
	
	public static partial class I___BaseItemConstants{

			public const string TemplateIdString = "c3799c90-e42b-43c5-a0d0-ac3f924252fb";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "__BaseItem";

			

	}

}
namespace Informa.Models.Informa.Models.sitecore.templates.User_Defined.Objects
{


 	/// <summary>
	/// IStaff_Item Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Objects/Staff Item</para>	
	/// <para>ID: daf954e3-bcc7-4353-996f-1caf9d35b44c</para>	
	/// </summary>
	[SitecoreType(TemplateId=IStaff_ItemConstants.TemplateIdString)]
	public partial interface IStaff_Item : IGlassBase 
	{
				}

	
		/// <summary>
		/// IStaff_Item Interface
		/// <para></para>
		/// <para>Path: /sitecore/templates/User Defined/Objects/Staff Item</para>	
		/// <para>ID: daf954e3-bcc7-4353-996f-1caf9d35b44c</para>	
		/// </summary>
		[SitecoreType]
		public partial interface IStaff_Item__Raw : IGlassBase 
		{
						}
	
	public static partial class IStaff_ItemConstants{

			public const string TemplateIdString = "daf954e3-bcc7-4353-996f-1caf9d35b44c";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Staff Item";

			

	}

}
namespace Informa.Models.Informa.Models.sitecore.templates.System.Layout.Sections
{


 	/// <summary>
	/// ICaching Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/System/Layout/Sections/Caching</para>	
	/// <para>ID: e8d2dd19-1347-4562-ae3f-310dc0b21a6c</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICachingConstants.TemplateIdString)]
	public partial interface ICaching : IGlassBase 
	{
								/// <summary>
					/// The Cacheable field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 3d08db46-2267-41b0-bc52-be69fd618633</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.CacheableFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool Cacheable  {get; set;}
								/// <summary>
					/// The CacheGETOnly field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 56ecb535-d06f-4b58-9169-78149c967010</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.CacheGETOnlyFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool CacheGETOnly  {get; set;}
								/// <summary>
					/// The ClearOnIndexUpdate field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: f3e7e552-d7c8-469b-a150-69e4e14ab35c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.ClearOnIndexUpdateFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool ClearOnIndexUpdate  {get; set;}
								/// <summary>
					/// The VaryByCustom field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 4a4a8085-08dc-4978-8d42-0c034e10cbe8</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.VaryByCustomFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool VaryByCustom  {get; set;}
								/// <summary>
					/// The VaryByCustomType field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 77dc6e45-2ac5-4c5f-a398-da54ff5f06c9</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.VaryByCustomTypeFieldName, Setting = SitecoreFieldSettings.InferType)]
					string VaryByCustomType  {get; set;}
								/// <summary>
					/// The VaryByData field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 8b6d532b-6128-4486-a044-ca06d90948ba</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.VaryByDataFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool VaryByData  {get; set;}
								/// <summary>
					/// The VaryByDevice field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: c98cf969-ba71-42da-833d-b3fc1368ba27</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.VaryByDeviceFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool VaryByDevice  {get; set;}
								/// <summary>
					/// The VaryByLogin field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 8d9232b0-613f-440b-a2fa-dcdd80fbd33e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.VaryByLoginFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool VaryByLogin  {get; set;}
								/// <summary>
					/// The VaryByParm field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 3ad2506a-dc39-4b1e-959f-9d524addbf50</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.VaryByParmFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool VaryByParm  {get; set;}
								/// <summary>
					/// The VaryByQueryString field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 1084d3d2-0457-456a-abbc-eb4cc0966072</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.VaryByQueryStringFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool VaryByQueryString  {get; set;}
								/// <summary>
					/// The VaryByUser field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 0e54a8dc-72ad-4372-a7c7-bb4773fad44d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.VaryByUserFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool VaryByUser  {get; set;}
				}

	
		/// <summary>
		/// ICaching Interface
		/// <para></para>
		/// <para>Path: /sitecore/templates/System/Layout/Sections/Caching</para>	
		/// <para>ID: e8d2dd19-1347-4562-ae3f-310dc0b21a6c</para>	
		/// </summary>
		[SitecoreType]
		public partial interface ICaching__Raw : IGlassBase 
		{
										/// <summary>
						/// The Cacheable field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: 3d08db46-2267-41b0-bc52-be69fd618633</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.CacheableFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool Cacheable  {get; set;}
										/// <summary>
						/// The CacheGETOnly field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: 56ecb535-d06f-4b58-9169-78149c967010</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.CacheGETOnlyFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool CacheGETOnly  {get; set;}
										/// <summary>
						/// The ClearOnIndexUpdate field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: f3e7e552-d7c8-469b-a150-69e4e14ab35c</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.ClearOnIndexUpdateFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool ClearOnIndexUpdate  {get; set;}
										/// <summary>
						/// The VaryByCustom field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: 4a4a8085-08dc-4978-8d42-0c034e10cbe8</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.VaryByCustomFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool VaryByCustom  {get; set;}
										/// <summary>
						/// The VaryByCustomType field.
						/// <para></para>
						/// <para>Field Type: Single-Line Text</para>		
						/// <para>Field ID: 77dc6e45-2ac5-4c5f-a398-da54ff5f06c9</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.VaryByCustomTypeFieldName, Setting = SitecoreFieldSettings.InferType)]
						string VaryByCustomType  {get; set;}
										/// <summary>
						/// The VaryByData field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: 8b6d532b-6128-4486-a044-ca06d90948ba</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.VaryByDataFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool VaryByData  {get; set;}
										/// <summary>
						/// The VaryByDevice field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: c98cf969-ba71-42da-833d-b3fc1368ba27</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.VaryByDeviceFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool VaryByDevice  {get; set;}
										/// <summary>
						/// The VaryByLogin field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: 8d9232b0-613f-440b-a2fa-dcdd80fbd33e</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.VaryByLoginFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool VaryByLogin  {get; set;}
										/// <summary>
						/// The VaryByParm field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: 3ad2506a-dc39-4b1e-959f-9d524addbf50</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.VaryByParmFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool VaryByParm  {get; set;}
										/// <summary>
						/// The VaryByQueryString field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: 1084d3d2-0457-456a-abbc-eb4cc0966072</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.VaryByQueryStringFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool VaryByQueryString  {get; set;}
										/// <summary>
						/// The VaryByUser field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: 0e54a8dc-72ad-4372-a7c7-bb4773fad44d</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.VaryByUserFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool VaryByUser  {get; set;}
						}
	
	public static partial class ICachingConstants{

			public const string TemplateIdString = "e8d2dd19-1347-4562-ae3f-310dc0b21a6c";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Caching";

					
			public static readonly ID CacheableFieldId = new ID("3d08db46-2267-41b0-bc52-be69fd618633");
			public const string CacheableFieldName = "Cacheable";

						
					
			public static readonly ID CacheGETOnlyFieldId = new ID("56ecb535-d06f-4b58-9169-78149c967010");
			public const string CacheGETOnlyFieldName = "CacheGETOnly";

						
					
			public static readonly ID ClearOnIndexUpdateFieldId = new ID("f3e7e552-d7c8-469b-a150-69e4e14ab35c");
			public const string ClearOnIndexUpdateFieldName = "ClearOnIndexUpdate";

						
					
			public static readonly ID VaryByCustomFieldId = new ID("4a4a8085-08dc-4978-8d42-0c034e10cbe8");
			public const string VaryByCustomFieldName = "VaryByCustom";

						
					
			public static readonly ID VaryByCustomTypeFieldId = new ID("77dc6e45-2ac5-4c5f-a398-da54ff5f06c9");
			public const string VaryByCustomTypeFieldName = "VaryByCustomType";

						
					
			public static readonly ID VaryByDataFieldId = new ID("8b6d532b-6128-4486-a044-ca06d90948ba");
			public const string VaryByDataFieldName = "VaryByData";

						
					
			public static readonly ID VaryByDeviceFieldId = new ID("c98cf969-ba71-42da-833d-b3fc1368ba27");
			public const string VaryByDeviceFieldName = "VaryByDevice";

						
					
			public static readonly ID VaryByLoginFieldId = new ID("8d9232b0-613f-440b-a2fa-dcdd80fbd33e");
			public const string VaryByLoginFieldName = "VaryByLogin";

						
					
			public static readonly ID VaryByParmFieldId = new ID("3ad2506a-dc39-4b1e-959f-9d524addbf50");
			public const string VaryByParmFieldName = "VaryByParm";

						
					
			public static readonly ID VaryByQueryStringFieldId = new ID("1084d3d2-0457-456a-abbc-eb4cc0966072");
			public const string VaryByQueryStringFieldName = "VaryByQueryString";

						
					
			public static readonly ID VaryByUserFieldId = new ID("0e54a8dc-72ad-4372-a7c7-bb4773fad44d");
			public const string VaryByUserFieldName = "VaryByUser";

						
			

	}

}
