





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Collections.Specialized;
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Jabberwocky.Glass.Models;
using Sitecore.Globalization;
using Sitecore.Data;



namespace Informa.Models.Informa.Models.sitecore.templates.User_Defined
{


 	/// <summary>
	/// IAuthored_Content Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Authored Content</para>	
	/// <para>ID: bc9061e8-27c6-4dd4-b342-50547e4a25cc</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAuthored_ContentConstants.TemplateIdString)]
	public partial interface IAuthored_Content : IGlassBase 
	{
								/// <summary>
					/// The Body field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 423ba8be-c356-44de-a608-361f09818330</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAuthored_ContentConstants.BodyFieldName, Setting = SitecoreFieldSettings.InferType)]
					string Body  {get; set;}
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: b820f81e-734a-4ef5-b35e-210b406aee13</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAuthored_ContentConstants.TitleFieldName, Setting = SitecoreFieldSettings.InferType)]
					string Title  {get; set;}
				}

	
		/// <summary>
		/// IAuthored_Content Interface
		/// <para></para>
		/// <para>Path: /sitecore/templates/User Defined/Authored Content</para>	
		/// <para>ID: bc9061e8-27c6-4dd4-b342-50547e4a25cc</para>	
		/// </summary>
		[SitecoreType]
		public partial interface IAuthored_Content__Raw : IGlassBase 
		{
										/// <summary>
						/// The Body field.
						/// <para></para>
						/// <para>Field Type: Rich Text</para>		
						/// <para>Field ID: 423ba8be-c356-44de-a608-361f09818330</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(IAuthored_ContentConstants.BodyFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
						string Body  {get; set;}
										/// <summary>
						/// The Title field.
						/// <para></para>
						/// <para>Field Type: Single-Line Text</para>		
						/// <para>Field ID: b820f81e-734a-4ef5-b35e-210b406aee13</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(IAuthored_ContentConstants.TitleFieldName, Setting = SitecoreFieldSettings.InferType)]
						string Title  {get; set;}
						}
	
	public static partial class IAuthored_ContentConstants{

			public const string TemplateIdString = "bc9061e8-27c6-4dd4-b342-50547e4a25cc";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Authored Content";

					
			public static readonly ID BodyFieldId = new ID("423ba8be-c356-44de-a608-361f09818330");
			public const string BodyFieldName = "Body";

							public static readonly ID Body__RawFieldId = new ID("423ba8be-c356-44de-a608-361f09818330");
				public const string Body__RawFieldName = "Body";
						
					
			public static readonly ID TitleFieldId = new ID("b820f81e-734a-4ef5-b35e-210b406aee13");
			public const string TitleFieldName = "Title";

						
			

	}

}
namespace Informa.Models.Informa.Models.sitecore.templates.System.Layout.Sections
{


 	/// <summary>
	/// ICaching Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/System/Layout/Sections/Caching</para>	
	/// <para>ID: e8d2dd19-1347-4562-ae3f-310dc0b21a6c</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICachingConstants.TemplateIdString)]
	public partial interface ICaching : IGlassBase 
	{
								/// <summary>
					/// The Cacheable field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 3d08db46-2267-41b0-bc52-be69fd618633</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.CacheableFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool Cacheable  {get; set;}
								/// <summary>
					/// The CacheGETOnly field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 56ecb535-d06f-4b58-9169-78149c967010</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.CacheGETOnlyFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool CacheGETOnly  {get; set;}
								/// <summary>
					/// The ClearOnIndexUpdate field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: f3e7e552-d7c8-469b-a150-69e4e14ab35c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.ClearOnIndexUpdateFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool ClearOnIndexUpdate  {get; set;}
								/// <summary>
					/// The VaryByCustom field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 4a4a8085-08dc-4978-8d42-0c034e10cbe8</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.VaryByCustomFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool VaryByCustom  {get; set;}
								/// <summary>
					/// The VaryByCustomType field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 77dc6e45-2ac5-4c5f-a398-da54ff5f06c9</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.VaryByCustomTypeFieldName, Setting = SitecoreFieldSettings.InferType)]
					string VaryByCustomType  {get; set;}
								/// <summary>
					/// The VaryByData field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 8b6d532b-6128-4486-a044-ca06d90948ba</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.VaryByDataFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool VaryByData  {get; set;}
								/// <summary>
					/// The VaryByDevice field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: c98cf969-ba71-42da-833d-b3fc1368ba27</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.VaryByDeviceFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool VaryByDevice  {get; set;}
								/// <summary>
					/// The VaryByLogin field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 8d9232b0-613f-440b-a2fa-dcdd80fbd33e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.VaryByLoginFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool VaryByLogin  {get; set;}
								/// <summary>
					/// The VaryByParm field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 3ad2506a-dc39-4b1e-959f-9d524addbf50</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.VaryByParmFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool VaryByParm  {get; set;}
								/// <summary>
					/// The VaryByQueryString field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 1084d3d2-0457-456a-abbc-eb4cc0966072</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.VaryByQueryStringFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool VaryByQueryString  {get; set;}
								/// <summary>
					/// The VaryByUser field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 0e54a8dc-72ad-4372-a7c7-bb4773fad44d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICachingConstants.VaryByUserFieldName, Setting = SitecoreFieldSettings.InferType)]
					bool VaryByUser  {get; set;}
				}

	
		/// <summary>
		/// ICaching Interface
		/// <para></para>
		/// <para>Path: /sitecore/templates/System/Layout/Sections/Caching</para>	
		/// <para>ID: e8d2dd19-1347-4562-ae3f-310dc0b21a6c</para>	
		/// </summary>
		[SitecoreType]
		public partial interface ICaching__Raw : IGlassBase 
		{
										/// <summary>
						/// The Cacheable field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: 3d08db46-2267-41b0-bc52-be69fd618633</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.CacheableFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool Cacheable  {get; set;}
										/// <summary>
						/// The CacheGETOnly field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: 56ecb535-d06f-4b58-9169-78149c967010</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.CacheGETOnlyFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool CacheGETOnly  {get; set;}
										/// <summary>
						/// The ClearOnIndexUpdate field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: f3e7e552-d7c8-469b-a150-69e4e14ab35c</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.ClearOnIndexUpdateFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool ClearOnIndexUpdate  {get; set;}
										/// <summary>
						/// The VaryByCustom field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: 4a4a8085-08dc-4978-8d42-0c034e10cbe8</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.VaryByCustomFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool VaryByCustom  {get; set;}
										/// <summary>
						/// The VaryByCustomType field.
						/// <para></para>
						/// <para>Field Type: Single-Line Text</para>		
						/// <para>Field ID: 77dc6e45-2ac5-4c5f-a398-da54ff5f06c9</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.VaryByCustomTypeFieldName, Setting = SitecoreFieldSettings.InferType)]
						string VaryByCustomType  {get; set;}
										/// <summary>
						/// The VaryByData field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: 8b6d532b-6128-4486-a044-ca06d90948ba</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.VaryByDataFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool VaryByData  {get; set;}
										/// <summary>
						/// The VaryByDevice field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: c98cf969-ba71-42da-833d-b3fc1368ba27</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.VaryByDeviceFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool VaryByDevice  {get; set;}
										/// <summary>
						/// The VaryByLogin field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: 8d9232b0-613f-440b-a2fa-dcdd80fbd33e</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.VaryByLoginFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool VaryByLogin  {get; set;}
										/// <summary>
						/// The VaryByParm field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: 3ad2506a-dc39-4b1e-959f-9d524addbf50</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.VaryByParmFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool VaryByParm  {get; set;}
										/// <summary>
						/// The VaryByQueryString field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: 1084d3d2-0457-456a-abbc-eb4cc0966072</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.VaryByQueryStringFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool VaryByQueryString  {get; set;}
										/// <summary>
						/// The VaryByUser field.
						/// <para></para>
						/// <para>Field Type: Checkbox</para>		
						/// <para>Field ID: 0e54a8dc-72ad-4372-a7c7-bb4773fad44d</para>
						/// <para>Custom Data: </para>
						/// </summary>
						[SitecoreField(ICachingConstants.VaryByUserFieldName, Setting = SitecoreFieldSettings.InferType)]
						bool VaryByUser  {get; set;}
						}
	
	public static partial class ICachingConstants{

			public const string TemplateIdString = "e8d2dd19-1347-4562-ae3f-310dc0b21a6c";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Caching";

					
			public static readonly ID CacheableFieldId = new ID("3d08db46-2267-41b0-bc52-be69fd618633");
			public const string CacheableFieldName = "Cacheable";

						
					
			public static readonly ID CacheGETOnlyFieldId = new ID("56ecb535-d06f-4b58-9169-78149c967010");
			public const string CacheGETOnlyFieldName = "CacheGETOnly";

						
					
			public static readonly ID ClearOnIndexUpdateFieldId = new ID("f3e7e552-d7c8-469b-a150-69e4e14ab35c");
			public const string ClearOnIndexUpdateFieldName = "ClearOnIndexUpdate";

						
					
			public static readonly ID VaryByCustomFieldId = new ID("4a4a8085-08dc-4978-8d42-0c034e10cbe8");
			public const string VaryByCustomFieldName = "VaryByCustom";

						
					
			public static readonly ID VaryByCustomTypeFieldId = new ID("77dc6e45-2ac5-4c5f-a398-da54ff5f06c9");
			public const string VaryByCustomTypeFieldName = "VaryByCustomType";

						
					
			public static readonly ID VaryByDataFieldId = new ID("8b6d532b-6128-4486-a044-ca06d90948ba");
			public const string VaryByDataFieldName = "VaryByData";

						
					
			public static readonly ID VaryByDeviceFieldId = new ID("c98cf969-ba71-42da-833d-b3fc1368ba27");
			public const string VaryByDeviceFieldName = "VaryByDevice";

						
					
			public static readonly ID VaryByLoginFieldId = new ID("8d9232b0-613f-440b-a2fa-dcdd80fbd33e");
			public const string VaryByLoginFieldName = "VaryByLogin";

						
					
			public static readonly ID VaryByParmFieldId = new ID("3ad2506a-dc39-4b1e-959f-9d524addbf50");
			public const string VaryByParmFieldName = "VaryByParm";

						
					
			public static readonly ID VaryByQueryStringFieldId = new ID("1084d3d2-0457-456a-abbc-eb4cc0966072");
			public const string VaryByQueryStringFieldName = "VaryByQueryString";

						
					
			public static readonly ID VaryByUserFieldId = new ID("0e54a8dc-72ad-4372-a7c7-bb4773fad44d");
			public const string VaryByUserFieldName = "VaryByUser";

						
			

	}

}
