//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="SCServerSoap", Namespace="https://tempuri.org/")]
public partial class SCServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback CreateArticleOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreatePubArticleOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreatePubArtGetOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreatePubArtGetDateOperationCompleted;
    
    private System.Threading.SendOrPostCallback SaveArticleDetailsOperationCompleted;
    
    private System.Threading.SendOrPostCallback SaveUnversionedArticleDetailsOperationCompleted;
    
    private System.Threading.SendOrPostCallback SaveArticleDetailsByGuidOperationCompleted;
    
    private System.Threading.SendOrPostCallback SaveArticleTextOperationCompleted;
    
    private System.Threading.SendOrPostCallback SaveArticleTextByGuidOperationCompleted;
    
    private System.Threading.SendOrPostCallback CheckOutArticleOperationCompleted;
    
    private System.Threading.SendOrPostCallback CheckOutArticleGuidOperationCompleted;
    
    private System.Threading.SendOrPostCallback CheckInArticleOperationCompleted;
    
    private System.Threading.SendOrPostCallback CheckInArticleGuidOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetLockedStatusOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetLockedStatusByGuidOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendDocumentToSitecoreOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendDocumentToSitecoreByGuidOperationCompleted;
    
    /// <remarks/>
    public SCServer() {
        this.Url = "http://ibi.arron.velir.com/services/scserver.asmx";
    }
    
    /// <remarks/>
    public event CreateArticleCompletedEventHandler CreateArticleCompleted;
    
    /// <remarks/>
    public event CreatePubArticleCompletedEventHandler CreatePubArticleCompleted;
    
    /// <remarks/>
    public event CreatePubArtGetCompletedEventHandler CreatePubArtGetCompleted;
    
    /// <remarks/>
    public event CreatePubArtGetDateCompletedEventHandler CreatePubArtGetDateCompleted;
    
    /// <remarks/>
    public event SaveArticleDetailsCompletedEventHandler SaveArticleDetailsCompleted;
    
    /// <remarks/>
    public event SaveUnversionedArticleDetailsCompletedEventHandler SaveUnversionedArticleDetailsCompleted;
    
    /// <remarks/>
    public event SaveArticleDetailsByGuidCompletedEventHandler SaveArticleDetailsByGuidCompleted;
    
    /// <remarks/>
    public event SaveArticleTextCompletedEventHandler SaveArticleTextCompleted;
    
    /// <remarks/>
    public event SaveArticleTextByGuidCompletedEventHandler SaveArticleTextByGuidCompleted;
    
    /// <remarks/>
    public event CheckOutArticleCompletedEventHandler CheckOutArticleCompleted;
    
    /// <remarks/>
    public event CheckOutArticleGuidCompletedEventHandler CheckOutArticleGuidCompleted;
    
    /// <remarks/>
    public event CheckInArticleCompletedEventHandler CheckInArticleCompleted;
    
    /// <remarks/>
    public event CheckInArticleGuidCompletedEventHandler CheckInArticleGuidCompleted;
    
    /// <remarks/>
    public event GetLockedStatusCompletedEventHandler GetLockedStatusCompleted;
    
    /// <remarks/>
    public event GetLockedStatusByGuidCompletedEventHandler GetLockedStatusByGuidCompleted;
    
    /// <remarks/>
    public event SendDocumentToSitecoreCompletedEventHandler SendDocumentToSitecoreCompleted;
    
    /// <remarks/>
    public event SendDocumentToSitecoreByGuidCompletedEventHandler SendDocumentToSitecoreByGuidCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/CreateArticle", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string CreateArticle(string articleName, string publicationDate, System.Guid publicationID, System.Guid publicationIssue, string username, string password) {
        object[] results = this.Invoke("CreateArticle", new object[] {
                    articleName,
                    publicationDate,
                    publicationID,
                    publicationIssue,
                    username,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateArticle(string articleName, string publicationDate, System.Guid publicationID, System.Guid publicationIssue, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateArticle", new object[] {
                    articleName,
                    publicationDate,
                    publicationID,
                    publicationIssue,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndCreateArticle(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void CreateArticleAsync(string articleName, string publicationDate, System.Guid publicationID, System.Guid publicationIssue, string username, string password) {
        this.CreateArticleAsync(articleName, publicationDate, publicationID, publicationIssue, username, password, null);
    }
    
    /// <remarks/>
    public void CreateArticleAsync(string articleName, string publicationDate, System.Guid publicationID, System.Guid publicationIssue, string username, string password, object userState) {
        if ((this.CreateArticleOperationCompleted == null)) {
            this.CreateArticleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateArticleOperationCompleted);
        }
        this.InvokeAsync("CreateArticle", new object[] {
                    articleName,
                    publicationDate,
                    publicationID,
                    publicationIssue,
                    username,
                    password}, this.CreateArticleOperationCompleted, userState);
    }
    
    private void OnCreateArticleOperationCompleted(object arg) {
        if ((this.CreateArticleCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateArticleCompleted(this, new CreateArticleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/CreatePubArticle", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string CreatePubArticle(string articleName, string publicationDate, System.Guid publicationID, System.Guid publicationIssue, string username, string password) {
        object[] results = this.Invoke("CreatePubArticle", new object[] {
                    articleName,
                    publicationDate,
                    publicationID,
                    publicationIssue,
                    username,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreatePubArticle(string articleName, string publicationDate, System.Guid publicationID, System.Guid publicationIssue, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreatePubArticle", new object[] {
                    articleName,
                    publicationDate,
                    publicationID,
                    publicationIssue,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndCreatePubArticle(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void CreatePubArticleAsync(string articleName, string publicationDate, System.Guid publicationID, System.Guid publicationIssue, string username, string password) {
        this.CreatePubArticleAsync(articleName, publicationDate, publicationID, publicationIssue, username, password, null);
    }
    
    /// <remarks/>
    public void CreatePubArticleAsync(string articleName, string publicationDate, System.Guid publicationID, System.Guid publicationIssue, string username, string password, object userState) {
        if ((this.CreatePubArticleOperationCompleted == null)) {
            this.CreatePubArticleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePubArticleOperationCompleted);
        }
        this.InvokeAsync("CreatePubArticle", new object[] {
                    articleName,
                    publicationDate,
                    publicationID,
                    publicationIssue,
                    username,
                    password}, this.CreatePubArticleOperationCompleted, userState);
    }
    
    private void OnCreatePubArticleOperationCompleted(object arg) {
        if ((this.CreatePubArticleCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreatePubArticleCompleted(this, new CreatePubArticleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/CreatePubArtGet", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ArticleStruct CreatePubArtGet(string articleName, string publicationDate, System.Guid publicationID, System.Guid publicationIssue, string username, string password) {
        object[] results = this.Invoke("CreatePubArtGet", new object[] {
                    articleName,
                    publicationDate,
                    publicationID,
                    publicationIssue,
                    username,
                    password});
        return ((ArticleStruct)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreatePubArtGet(string articleName, string publicationDate, System.Guid publicationID, System.Guid publicationIssue, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreatePubArtGet", new object[] {
                    articleName,
                    publicationDate,
                    publicationID,
                    publicationIssue,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public ArticleStruct EndCreatePubArtGet(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ArticleStruct)(results[0]));
    }
    
    /// <remarks/>
    public void CreatePubArtGetAsync(string articleName, string publicationDate, System.Guid publicationID, System.Guid publicationIssue, string username, string password) {
        this.CreatePubArtGetAsync(articleName, publicationDate, publicationID, publicationIssue, username, password, null);
    }
    
    /// <remarks/>
    public void CreatePubArtGetAsync(string articleName, string publicationDate, System.Guid publicationID, System.Guid publicationIssue, string username, string password, object userState) {
        if ((this.CreatePubArtGetOperationCompleted == null)) {
            this.CreatePubArtGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePubArtGetOperationCompleted);
        }
        this.InvokeAsync("CreatePubArtGet", new object[] {
                    articleName,
                    publicationDate,
                    publicationID,
                    publicationIssue,
                    username,
                    password}, this.CreatePubArtGetOperationCompleted, userState);
    }
    
    private void OnCreatePubArtGetOperationCompleted(object arg) {
        if ((this.CreatePubArtGetCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreatePubArtGetCompleted(this, new CreatePubArtGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/CreatePubArtGetDate", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ArticleStruct CreatePubArtGetDate(string articleName, System.DateTime publicationDate, System.Guid publicationID, System.Guid publicationIssue, string username, string password) {
        object[] results = this.Invoke("CreatePubArtGetDate", new object[] {
                    articleName,
                    publicationDate,
                    publicationID,
                    publicationIssue,
                    username,
                    password});
        return ((ArticleStruct)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreatePubArtGetDate(string articleName, System.DateTime publicationDate, System.Guid publicationID, System.Guid publicationIssue, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreatePubArtGetDate", new object[] {
                    articleName,
                    publicationDate,
                    publicationID,
                    publicationIssue,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public ArticleStruct EndCreatePubArtGetDate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ArticleStruct)(results[0]));
    }
    
    /// <remarks/>
    public void CreatePubArtGetDateAsync(string articleName, System.DateTime publicationDate, System.Guid publicationID, System.Guid publicationIssue, string username, string password) {
        this.CreatePubArtGetDateAsync(articleName, publicationDate, publicationID, publicationIssue, username, password, null);
    }
    
    /// <remarks/>
    public void CreatePubArtGetDateAsync(string articleName, System.DateTime publicationDate, System.Guid publicationID, System.Guid publicationIssue, string username, string password, object userState) {
        if ((this.CreatePubArtGetDateOperationCompleted == null)) {
            this.CreatePubArtGetDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePubArtGetDateOperationCompleted);
        }
        this.InvokeAsync("CreatePubArtGetDate", new object[] {
                    articleName,
                    publicationDate,
                    publicationID,
                    publicationIssue,
                    username,
                    password}, this.CreatePubArtGetDateOperationCompleted, userState);
    }
    
    private void OnCreatePubArtGetDateOperationCompleted(object arg) {
        if ((this.CreatePubArtGetDateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreatePubArtGetDateCompleted(this, new CreatePubArtGetDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/SaveArticleDetails", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SaveArticleDetails(string articleNumber, ArticleStruct articleData, string username, string password) {
        this.Invoke("SaveArticleDetails", new object[] {
                    articleNumber,
                    articleData,
                    username,
                    password});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSaveArticleDetails(string articleNumber, ArticleStruct articleData, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SaveArticleDetails", new object[] {
                    articleNumber,
                    articleData,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSaveArticleDetails(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SaveArticleDetailsAsync(string articleNumber, ArticleStruct articleData, string username, string password) {
        this.SaveArticleDetailsAsync(articleNumber, articleData, username, password, null);
    }
    
    /// <remarks/>
    public void SaveArticleDetailsAsync(string articleNumber, ArticleStruct articleData, string username, string password, object userState) {
        if ((this.SaveArticleDetailsOperationCompleted == null)) {
            this.SaveArticleDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveArticleDetailsOperationCompleted);
        }
        this.InvokeAsync("SaveArticleDetails", new object[] {
                    articleNumber,
                    articleData,
                    username,
                    password}, this.SaveArticleDetailsOperationCompleted, userState);
    }
    
    private void OnSaveArticleDetailsOperationCompleted(object arg) {
        if ((this.SaveArticleDetailsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SaveArticleDetailsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/SaveUnversionedArticleDetails", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SaveUnversionedArticleDetails(string articleNumber, ArticleStruct articleData, string username, string password) {
        this.Invoke("SaveUnversionedArticleDetails", new object[] {
                    articleNumber,
                    articleData,
                    username,
                    password});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSaveUnversionedArticleDetails(string articleNumber, ArticleStruct articleData, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SaveUnversionedArticleDetails", new object[] {
                    articleNumber,
                    articleData,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSaveUnversionedArticleDetails(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SaveUnversionedArticleDetailsAsync(string articleNumber, ArticleStruct articleData, string username, string password) {
        this.SaveUnversionedArticleDetailsAsync(articleNumber, articleData, username, password, null);
    }
    
    /// <remarks/>
    public void SaveUnversionedArticleDetailsAsync(string articleNumber, ArticleStruct articleData, string username, string password, object userState) {
        if ((this.SaveUnversionedArticleDetailsOperationCompleted == null)) {
            this.SaveUnversionedArticleDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveUnversionedArticleDetailsOperationCompleted);
        }
        this.InvokeAsync("SaveUnversionedArticleDetails", new object[] {
                    articleNumber,
                    articleData,
                    username,
                    password}, this.SaveUnversionedArticleDetailsOperationCompleted, userState);
    }
    
    private void OnSaveUnversionedArticleDetailsOperationCompleted(object arg) {
        if ((this.SaveUnversionedArticleDetailsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SaveUnversionedArticleDetailsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/SaveArticleDetailsByGuid", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SaveArticleDetailsByGuid(System.Guid articleGuid, ArticleStruct articleData, string username, string password) {
        this.Invoke("SaveArticleDetailsByGuid", new object[] {
                    articleGuid,
                    articleData,
                    username,
                    password});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSaveArticleDetailsByGuid(System.Guid articleGuid, ArticleStruct articleData, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SaveArticleDetailsByGuid", new object[] {
                    articleGuid,
                    articleData,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSaveArticleDetailsByGuid(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SaveArticleDetailsByGuidAsync(System.Guid articleGuid, ArticleStruct articleData, string username, string password) {
        this.SaveArticleDetailsByGuidAsync(articleGuid, articleData, username, password, null);
    }
    
    /// <remarks/>
    public void SaveArticleDetailsByGuidAsync(System.Guid articleGuid, ArticleStruct articleData, string username, string password, object userState) {
        if ((this.SaveArticleDetailsByGuidOperationCompleted == null)) {
            this.SaveArticleDetailsByGuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveArticleDetailsByGuidOperationCompleted);
        }
        this.InvokeAsync("SaveArticleDetailsByGuid", new object[] {
                    articleGuid,
                    articleData,
                    username,
                    password}, this.SaveArticleDetailsByGuidOperationCompleted, userState);
    }
    
    private void OnSaveArticleDetailsByGuidOperationCompleted(object arg) {
        if ((this.SaveArticleDetailsByGuidCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SaveArticleDetailsByGuidCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/SaveArticleText", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SaveArticleText(string articleNumber, string wordText, ArticleStruct articleData, string username, string password) {
        this.Invoke("SaveArticleText", new object[] {
                    articleNumber,
                    wordText,
                    articleData,
                    username,
                    password});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSaveArticleText(string articleNumber, string wordText, ArticleStruct articleData, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SaveArticleText", new object[] {
                    articleNumber,
                    wordText,
                    articleData,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSaveArticleText(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SaveArticleTextAsync(string articleNumber, string wordText, ArticleStruct articleData, string username, string password) {
        this.SaveArticleTextAsync(articleNumber, wordText, articleData, username, password, null);
    }
    
    /// <remarks/>
    public void SaveArticleTextAsync(string articleNumber, string wordText, ArticleStruct articleData, string username, string password, object userState) {
        if ((this.SaveArticleTextOperationCompleted == null)) {
            this.SaveArticleTextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveArticleTextOperationCompleted);
        }
        this.InvokeAsync("SaveArticleText", new object[] {
                    articleNumber,
                    wordText,
                    articleData,
                    username,
                    password}, this.SaveArticleTextOperationCompleted, userState);
    }
    
    private void OnSaveArticleTextOperationCompleted(object arg) {
        if ((this.SaveArticleTextCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SaveArticleTextCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/SaveArticleTextByGuid", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SaveArticleTextByGuid(System.Guid articleGuid, string wordText, ArticleStruct articleData, string username, string password) {
        this.Invoke("SaveArticleTextByGuid", new object[] {
                    articleGuid,
                    wordText,
                    articleData,
                    username,
                    password});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSaveArticleTextByGuid(System.Guid articleGuid, string wordText, ArticleStruct articleData, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SaveArticleTextByGuid", new object[] {
                    articleGuid,
                    wordText,
                    articleData,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSaveArticleTextByGuid(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SaveArticleTextByGuidAsync(System.Guid articleGuid, string wordText, ArticleStruct articleData, string username, string password) {
        this.SaveArticleTextByGuidAsync(articleGuid, wordText, articleData, username, password, null);
    }
    
    /// <remarks/>
    public void SaveArticleTextByGuidAsync(System.Guid articleGuid, string wordText, ArticleStruct articleData, string username, string password, object userState) {
        if ((this.SaveArticleTextByGuidOperationCompleted == null)) {
            this.SaveArticleTextByGuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveArticleTextByGuidOperationCompleted);
        }
        this.InvokeAsync("SaveArticleTextByGuid", new object[] {
                    articleGuid,
                    wordText,
                    articleData,
                    username,
                    password}, this.SaveArticleTextByGuidOperationCompleted, userState);
    }
    
    private void OnSaveArticleTextByGuidOperationCompleted(object arg) {
        if ((this.SaveArticleTextByGuidCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SaveArticleTextByGuidCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/CheckOutArticle", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool CheckOutArticle(string articleNumber, string userID, string username, string password) {
        object[] results = this.Invoke("CheckOutArticle", new object[] {
                    articleNumber,
                    userID,
                    username,
                    password});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCheckOutArticle(string articleNumber, string userID, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CheckOutArticle", new object[] {
                    articleNumber,
                    userID,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndCheckOutArticle(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void CheckOutArticleAsync(string articleNumber, string userID, string username, string password) {
        this.CheckOutArticleAsync(articleNumber, userID, username, password, null);
    }
    
    /// <remarks/>
    public void CheckOutArticleAsync(string articleNumber, string userID, string username, string password, object userState) {
        if ((this.CheckOutArticleOperationCompleted == null)) {
            this.CheckOutArticleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckOutArticleOperationCompleted);
        }
        this.InvokeAsync("CheckOutArticle", new object[] {
                    articleNumber,
                    userID,
                    username,
                    password}, this.CheckOutArticleOperationCompleted, userState);
    }
    
    private void OnCheckOutArticleOperationCompleted(object arg) {
        if ((this.CheckOutArticleCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CheckOutArticleCompleted(this, new CheckOutArticleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/CheckOutArticleGuid", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool CheckOutArticleGuid(System.Guid articleGuid, string userID, string username, string password) {
        object[] results = this.Invoke("CheckOutArticleGuid", new object[] {
                    articleGuid,
                    userID,
                    username,
                    password});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCheckOutArticleGuid(System.Guid articleGuid, string userID, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CheckOutArticleGuid", new object[] {
                    articleGuid,
                    userID,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndCheckOutArticleGuid(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void CheckOutArticleGuidAsync(System.Guid articleGuid, string userID, string username, string password) {
        this.CheckOutArticleGuidAsync(articleGuid, userID, username, password, null);
    }
    
    /// <remarks/>
    public void CheckOutArticleGuidAsync(System.Guid articleGuid, string userID, string username, string password, object userState) {
        if ((this.CheckOutArticleGuidOperationCompleted == null)) {
            this.CheckOutArticleGuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckOutArticleGuidOperationCompleted);
        }
        this.InvokeAsync("CheckOutArticleGuid", new object[] {
                    articleGuid,
                    userID,
                    username,
                    password}, this.CheckOutArticleGuidOperationCompleted, userState);
    }
    
    private void OnCheckOutArticleGuidOperationCompleted(object arg) {
        if ((this.CheckOutArticleGuidCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CheckOutArticleGuidCompleted(this, new CheckOutArticleGuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/CheckInArticle", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool CheckInArticle(string articleNumber, string username, string password) {
        object[] results = this.Invoke("CheckInArticle", new object[] {
                    articleNumber,
                    username,
                    password});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCheckInArticle(string articleNumber, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CheckInArticle", new object[] {
                    articleNumber,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndCheckInArticle(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void CheckInArticleAsync(string articleNumber, string username, string password) {
        this.CheckInArticleAsync(articleNumber, username, password, null);
    }
    
    /// <remarks/>
    public void CheckInArticleAsync(string articleNumber, string username, string password, object userState) {
        if ((this.CheckInArticleOperationCompleted == null)) {
            this.CheckInArticleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckInArticleOperationCompleted);
        }
        this.InvokeAsync("CheckInArticle", new object[] {
                    articleNumber,
                    username,
                    password}, this.CheckInArticleOperationCompleted, userState);
    }
    
    private void OnCheckInArticleOperationCompleted(object arg) {
        if ((this.CheckInArticleCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CheckInArticleCompleted(this, new CheckInArticleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/CheckInArticleGuid", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool CheckInArticleGuid(System.Guid articleGuid, string username, string password) {
        object[] results = this.Invoke("CheckInArticleGuid", new object[] {
                    articleGuid,
                    username,
                    password});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCheckInArticleGuid(System.Guid articleGuid, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CheckInArticleGuid", new object[] {
                    articleGuid,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndCheckInArticleGuid(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void CheckInArticleGuidAsync(System.Guid articleGuid, string username, string password) {
        this.CheckInArticleGuidAsync(articleGuid, username, password, null);
    }
    
    /// <remarks/>
    public void CheckInArticleGuidAsync(System.Guid articleGuid, string username, string password, object userState) {
        if ((this.CheckInArticleGuidOperationCompleted == null)) {
            this.CheckInArticleGuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckInArticleGuidOperationCompleted);
        }
        this.InvokeAsync("CheckInArticleGuid", new object[] {
                    articleGuid,
                    username,
                    password}, this.CheckInArticleGuidOperationCompleted, userState);
    }
    
    private void OnCheckInArticleGuidOperationCompleted(object arg) {
        if ((this.CheckInArticleGuidCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CheckInArticleGuidCompleted(this, new CheckInArticleGuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/GetLockedStatus", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public CheckoutStatus GetLockedStatus(string articleNumber, string username, string password) {
        object[] results = this.Invoke("GetLockedStatus", new object[] {
                    articleNumber,
                    username,
                    password});
        return ((CheckoutStatus)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetLockedStatus(string articleNumber, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetLockedStatus", new object[] {
                    articleNumber,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public CheckoutStatus EndGetLockedStatus(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CheckoutStatus)(results[0]));
    }
    
    /// <remarks/>
    public void GetLockedStatusAsync(string articleNumber, string username, string password) {
        this.GetLockedStatusAsync(articleNumber, username, password, null);
    }
    
    /// <remarks/>
    public void GetLockedStatusAsync(string articleNumber, string username, string password, object userState) {
        if ((this.GetLockedStatusOperationCompleted == null)) {
            this.GetLockedStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLockedStatusOperationCompleted);
        }
        this.InvokeAsync("GetLockedStatus", new object[] {
                    articleNumber,
                    username,
                    password}, this.GetLockedStatusOperationCompleted, userState);
    }
    
    private void OnGetLockedStatusOperationCompleted(object arg) {
        if ((this.GetLockedStatusCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetLockedStatusCompleted(this, new GetLockedStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/GetLockedStatusByGuid", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public CheckoutStatus GetLockedStatusByGuid(System.Guid articleGuid, string username, string password) {
        object[] results = this.Invoke("GetLockedStatusByGuid", new object[] {
                    articleGuid,
                    username,
                    password});
        return ((CheckoutStatus)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetLockedStatusByGuid(System.Guid articleGuid, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetLockedStatusByGuid", new object[] {
                    articleGuid,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public CheckoutStatus EndGetLockedStatusByGuid(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CheckoutStatus)(results[0]));
    }
    
    /// <remarks/>
    public void GetLockedStatusByGuidAsync(System.Guid articleGuid, string username, string password) {
        this.GetLockedStatusByGuidAsync(articleGuid, username, password, null);
    }
    
    /// <remarks/>
    public void GetLockedStatusByGuidAsync(System.Guid articleGuid, string username, string password, object userState) {
        if ((this.GetLockedStatusByGuidOperationCompleted == null)) {
            this.GetLockedStatusByGuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLockedStatusByGuidOperationCompleted);
        }
        this.InvokeAsync("GetLockedStatusByGuid", new object[] {
                    articleGuid,
                    username,
                    password}, this.GetLockedStatusByGuidOperationCompleted, userState);
    }
    
    private void OnGetLockedStatusByGuidOperationCompleted(object arg) {
        if ((this.GetLockedStatusByGuidCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetLockedStatusByGuidCompleted(this, new GetLockedStatusByGuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/SendDocumentToSitecore", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int SendDocumentToSitecore(string articleNumber, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] data, string extension, string username, string password) {
        object[] results = this.Invoke("SendDocumentToSitecore", new object[] {
                    articleNumber,
                    data,
                    extension,
                    username,
                    password});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendDocumentToSitecore(string articleNumber, byte[] data, string extension, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendDocumentToSitecore", new object[] {
                    articleNumber,
                    data,
                    extension,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndSendDocumentToSitecore(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void SendDocumentToSitecoreAsync(string articleNumber, byte[] data, string extension, string username, string password) {
        this.SendDocumentToSitecoreAsync(articleNumber, data, extension, username, password, null);
    }
    
    /// <remarks/>
    public void SendDocumentToSitecoreAsync(string articleNumber, byte[] data, string extension, string username, string password, object userState) {
        if ((this.SendDocumentToSitecoreOperationCompleted == null)) {
            this.SendDocumentToSitecoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendDocumentToSitecoreOperationCompleted);
        }
        this.InvokeAsync("SendDocumentToSitecore", new object[] {
                    articleNumber,
                    data,
                    extension,
                    username,
                    password}, this.SendDocumentToSitecoreOperationCompleted, userState);
    }
    
    private void OnSendDocumentToSitecoreOperationCompleted(object arg) {
        if ((this.SendDocumentToSitecoreCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendDocumentToSitecoreCompleted(this, new SendDocumentToSitecoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://tempuri.org/SendDocumentToSitecoreByGuid", RequestNamespace="https://tempuri.org/", ResponseNamespace="https://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int SendDocumentToSitecoreByGuid(System.Guid articlGuid, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] data, string extension, string username, string password) {
        object[] results = this.Invoke("SendDocumentToSitecoreByGuid", new object[] {
                    articlGuid,
                    data,
                    extension,
                    username,
                    password});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendDocumentToSitecoreByGuid(System.Guid articlGuid, byte[] data, string extension, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendDocumentToSitecoreByGuid", new object[] {
                    articlGuid,
                    data,
                    extension,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndSendDocumentToSitecoreByGuid(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void SendDocumentToSitecoreByGuidAsync(System.Guid articlGuid, byte[] data, string extension, string username, string password) {
        this.SendDocumentToSitecoreByGuidAsync(articlGuid, data, extension, username, password, null);
    }
    
    /// <remarks/>
    public void SendDocumentToSitecoreByGuidAsync(System.Guid articlGuid, byte[] data, string extension, string username, string password, object userState) {
        if ((this.SendDocumentToSitecoreByGuidOperationCompleted == null)) {
            this.SendDocumentToSitecoreByGuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendDocumentToSitecoreByGuidOperationCompleted);
        }
        this.InvokeAsync("SendDocumentToSitecoreByGuid", new object[] {
                    articlGuid,
                    data,
                    extension,
                    username,
                    password}, this.SendDocumentToSitecoreByGuidOperationCompleted, userState);
    }
    
    private void OnSendDocumentToSitecoreByGuidOperationCompleted(object arg) {
        if ((this.SendDocumentToSitecoreByGuidCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendDocumentToSitecoreByGuidCompleted(this, new SendDocumentToSitecoreByGuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://tempuri.org/")]
public partial class ArticleStruct {
    
    private System.Guid articleGuidField;
    
    private string titleField;
    
    private System.Guid volumeField;
    
    private System.Guid issueField;
    
    private System.DateTime printPublicationDateField;
    
    private System.DateTime webPublicationDateField;
    
    private string articleNumberField;
    
    private System.Guid articleCategoryField;
    
    private System.Guid webCategoryField;
    
    private string notesToEditorialField;
    
    private string notesToProductionField;
    
    private string subtitleField;
    
    private string longSummaryField;
    
    private string shortSummaryField;
    
    private string deckField;
    
    private int wordCountField;
    
    private bool isFeaturedArticleField;
    
    private bool hasBeenNominatedField;
    
    private bool isTopStoryField;
    
    private WorkflowState workflowStateField;
    
    private System.Guid commandIDField;
    
    private TaxonomyStruct[] industriesField;
    
    private TaxonomyStruct[] subjectsField;
    
    private TaxonomyStruct[] geographyField;
    
    private TaxonomyStruct[] therapeuticCategoriesField;
    
    private TaxonomyStruct[] marketSegmentsField;
    
    private System.Guid[] relatedInlineArticlesField;
    
    private System.Guid[] relatedArticlesField;
    
    private System.Guid[] childArticlesField;
    
    private string[] supportingDocumentPathsField;
    
    private TaxonomyStruct[] generalTagsField;
    
    private ArticlePreviewInfo[] referencedArticlesInfoField;
    
    private ArticlePreviewInfo[] relatedArticlesInfoField;
    
    private string[] referencedDealsField;
    
    private StaffStruct[] authorsField;
    
    private StaffStruct[] editorsField;
    
    private StaffStruct[] articleSpecificNotificationsField;
    
    private StaffStruct[] globalNotificationsField;
    
    private int wordDocVersionNumberField;
    
    private string wordDocLastUpdateDateField;
    
    private string wordDocLastUpdatedByField;
    
    private System.Guid publicationField;
    
    private bool embargoedField;
    
    private bool isPublishedField;
    
    /// <remarks/>
    public System.Guid ArticleGuid {
        get {
            return this.articleGuidField;
        }
        set {
            this.articleGuidField = value;
        }
    }
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid Volume {
        get {
            return this.volumeField;
        }
        set {
            this.volumeField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid Issue {
        get {
            return this.issueField;
        }
        set {
            this.issueField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime PrintPublicationDate {
        get {
            return this.printPublicationDateField;
        }
        set {
            this.printPublicationDateField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime WebPublicationDate {
        get {
            return this.webPublicationDateField;
        }
        set {
            this.webPublicationDateField = value;
        }
    }
    
    /// <remarks/>
    public string ArticleNumber {
        get {
            return this.articleNumberField;
        }
        set {
            this.articleNumberField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid ArticleCategory {
        get {
            return this.articleCategoryField;
        }
        set {
            this.articleCategoryField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid WebCategory {
        get {
            return this.webCategoryField;
        }
        set {
            this.webCategoryField = value;
        }
    }
    
    /// <remarks/>
    public string NotesToEditorial {
        get {
            return this.notesToEditorialField;
        }
        set {
            this.notesToEditorialField = value;
        }
    }
    
    /// <remarks/>
    public string NotesToProduction {
        get {
            return this.notesToProductionField;
        }
        set {
            this.notesToProductionField = value;
        }
    }
    
    /// <remarks/>
    public string Subtitle {
        get {
            return this.subtitleField;
        }
        set {
            this.subtitleField = value;
        }
    }
    
    /// <remarks/>
    public string LongSummary {
        get {
            return this.longSummaryField;
        }
        set {
            this.longSummaryField = value;
        }
    }
    
    /// <remarks/>
    public string ShortSummary {
        get {
            return this.shortSummaryField;
        }
        set {
            this.shortSummaryField = value;
        }
    }
    
    /// <remarks/>
    public string Deck {
        get {
            return this.deckField;
        }
        set {
            this.deckField = value;
        }
    }
    
    /// <remarks/>
    public int WordCount {
        get {
            return this.wordCountField;
        }
        set {
            this.wordCountField = value;
        }
    }
    
    /// <remarks/>
    public bool IsFeaturedArticle {
        get {
            return this.isFeaturedArticleField;
        }
        set {
            this.isFeaturedArticleField = value;
        }
    }
    
    /// <remarks/>
    public bool HasBeenNominated {
        get {
            return this.hasBeenNominatedField;
        }
        set {
            this.hasBeenNominatedField = value;
        }
    }
    
    /// <remarks/>
    public bool IsTopStory {
        get {
            return this.isTopStoryField;
        }
        set {
            this.isTopStoryField = value;
        }
    }
    
    /// <remarks/>
    public WorkflowState WorkflowState {
        get {
            return this.workflowStateField;
        }
        set {
            this.workflowStateField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid CommandID {
        get {
            return this.commandIDField;
        }
        set {
            this.commandIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public TaxonomyStruct[] Industries {
        get {
            return this.industriesField;
        }
        set {
            this.industriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public TaxonomyStruct[] Subjects {
        get {
            return this.subjectsField;
        }
        set {
            this.subjectsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public TaxonomyStruct[] Geography {
        get {
            return this.geographyField;
        }
        set {
            this.geographyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public TaxonomyStruct[] TherapeuticCategories {
        get {
            return this.therapeuticCategoriesField;
        }
        set {
            this.therapeuticCategoriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public TaxonomyStruct[] MarketSegments {
        get {
            return this.marketSegmentsField;
        }
        set {
            this.marketSegmentsField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid[] RelatedInlineArticles {
        get {
            return this.relatedInlineArticlesField;
        }
        set {
            this.relatedInlineArticlesField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid[] RelatedArticles {
        get {
            return this.relatedArticlesField;
        }
        set {
            this.relatedArticlesField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid[] ChildArticles {
        get {
            return this.childArticlesField;
        }
        set {
            this.childArticlesField = value;
        }
    }
    
    /// <remarks/>
    public string[] SupportingDocumentPaths {
        get {
            return this.supportingDocumentPathsField;
        }
        set {
            this.supportingDocumentPathsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public TaxonomyStruct[] GeneralTags {
        get {
            return this.generalTagsField;
        }
        set {
            this.generalTagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public ArticlePreviewInfo[] ReferencedArticlesInfo {
        get {
            return this.referencedArticlesInfoField;
        }
        set {
            this.referencedArticlesInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public ArticlePreviewInfo[] RelatedArticlesInfo {
        get {
            return this.relatedArticlesInfoField;
        }
        set {
            this.relatedArticlesInfoField = value;
        }
    }
    
    /// <remarks/>
    public string[] ReferencedDeals {
        get {
            return this.referencedDealsField;
        }
        set {
            this.referencedDealsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public StaffStruct[] Authors {
        get {
            return this.authorsField;
        }
        set {
            this.authorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public StaffStruct[] Editors {
        get {
            return this.editorsField;
        }
        set {
            this.editorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public StaffStruct[] ArticleSpecificNotifications {
        get {
            return this.articleSpecificNotificationsField;
        }
        set {
            this.articleSpecificNotificationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public StaffStruct[] GlobalNotifications {
        get {
            return this.globalNotificationsField;
        }
        set {
            this.globalNotificationsField = value;
        }
    }
    
    /// <remarks/>
    public int WordDocVersionNumber {
        get {
            return this.wordDocVersionNumberField;
        }
        set {
            this.wordDocVersionNumberField = value;
        }
    }
    
    /// <remarks/>
    public string WordDocLastUpdateDate {
        get {
            return this.wordDocLastUpdateDateField;
        }
        set {
            this.wordDocLastUpdateDateField = value;
        }
    }
    
    /// <remarks/>
    public string WordDocLastUpdatedBy {
        get {
            return this.wordDocLastUpdatedByField;
        }
        set {
            this.wordDocLastUpdatedByField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid Publication {
        get {
            return this.publicationField;
        }
        set {
            this.publicationField = value;
        }
    }
    
    /// <remarks/>
    public bool Embargoed {
        get {
            return this.embargoedField;
        }
        set {
            this.embargoedField = value;
        }
    }
    
    /// <remarks/>
    public bool IsPublished {
        get {
            return this.isPublishedField;
        }
        set {
            this.isPublishedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://tempuri.org/")]
public partial class WorkflowState {
    
    private string displayNameField;
    
    private WorkflowCommand[] commandsField;
    
    private bool isFinalField;
    
    /// <remarks/>
    public string DisplayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public WorkflowCommand[] Commands {
        get {
            return this.commandsField;
        }
        set {
            this.commandsField = value;
        }
    }
    
    /// <remarks/>
    public bool IsFinal {
        get {
            return this.isFinalField;
        }
        set {
            this.isFinalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://tempuri.org/")]
public partial class WorkflowCommand {
    
    private string displayNameField;
    
    private string stringIDField;
    
    private StaffStruct[] globalNotifyListField;
    
    private bool sendsToFinalField;
    
    /// <remarks/>
    public string DisplayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
    
    /// <remarks/>
    public string StringID {
        get {
            return this.stringIDField;
        }
        set {
            this.stringIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public StaffStruct[] GlobalNotifyList {
        get {
            return this.globalNotifyListField;
        }
        set {
            this.globalNotifyListField = value;
        }
    }
    
    /// <remarks/>
    public bool SendsToFinal {
        get {
            return this.sendsToFinalField;
        }
        set {
            this.sendsToFinalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://tempuri.org/")]
public partial class StaffStruct {
    
    private string nameField;
    
    private System.Guid[] publicationsField;
    
    private System.Guid idField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid[] Publications {
        get {
            return this.publicationsField;
        }
        set {
            this.publicationsField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://tempuri.org/")]
public partial class CheckoutStatus {
    
    private string userField;
    
    private bool lockedField;
    
    /// <remarks/>
    public string User {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    public bool Locked {
        get {
            return this.lockedField;
        }
        set {
            this.lockedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://tempuri.org/")]
public partial class ArticlePreviewInfo {
    
    private string titleField;
    
    private string[] authorsField;
    
    private string articleNumberField;
    
    private string publicationField;
    
    private System.DateTime dateField;
    
    private string previewUrlField;
    
    private System.Guid guidField;
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string[] Authors {
        get {
            return this.authorsField;
        }
        set {
            this.authorsField = value;
        }
    }
    
    /// <remarks/>
    public string ArticleNumber {
        get {
            return this.articleNumberField;
        }
        set {
            this.articleNumberField = value;
        }
    }
    
    /// <remarks/>
    public string Publication {
        get {
            return this.publicationField;
        }
        set {
            this.publicationField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    public string PreviewUrl {
        get {
            return this.previewUrlField;
        }
        set {
            this.previewUrlField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid Guid {
        get {
            return this.guidField;
        }
        set {
            this.guidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://tempuri.org/")]
public partial class TaxonomyStruct {
    
    private string nameField;
    
    private System.Guid idField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CreateArticleCompletedEventHandler(object sender, CreateArticleCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateArticleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateArticleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CreatePubArticleCompletedEventHandler(object sender, CreatePubArticleCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreatePubArticleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreatePubArticleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CreatePubArtGetCompletedEventHandler(object sender, CreatePubArtGetCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreatePubArtGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreatePubArtGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ArticleStruct Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ArticleStruct)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CreatePubArtGetDateCompletedEventHandler(object sender, CreatePubArtGetDateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreatePubArtGetDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreatePubArtGetDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ArticleStruct Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ArticleStruct)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SaveArticleDetailsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SaveUnversionedArticleDetailsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SaveArticleDetailsByGuidCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SaveArticleTextCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SaveArticleTextByGuidCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CheckOutArticleCompletedEventHandler(object sender, CheckOutArticleCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CheckOutArticleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CheckOutArticleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CheckOutArticleGuidCompletedEventHandler(object sender, CheckOutArticleGuidCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CheckOutArticleGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CheckOutArticleGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CheckInArticleCompletedEventHandler(object sender, CheckInArticleCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CheckInArticleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CheckInArticleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CheckInArticleGuidCompletedEventHandler(object sender, CheckInArticleGuidCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CheckInArticleGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CheckInArticleGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetLockedStatusCompletedEventHandler(object sender, GetLockedStatusCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetLockedStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetLockedStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CheckoutStatus Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CheckoutStatus)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetLockedStatusByGuidCompletedEventHandler(object sender, GetLockedStatusByGuidCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetLockedStatusByGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetLockedStatusByGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CheckoutStatus Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CheckoutStatus)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SendDocumentToSitecoreCompletedEventHandler(object sender, SendDocumentToSitecoreCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SendDocumentToSitecoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SendDocumentToSitecoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SendDocumentToSitecoreByGuidCompletedEventHandler(object sender, SendDocumentToSitecoreByGuidCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SendDocumentToSitecoreByGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SendDocumentToSitecoreByGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}
