//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informa.Models.DealsCompaniesDrugs
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyRecordImportLog
    {
        public int Id { get; set; }
        public Nullable<int> RecordId { get; set; }
        public int ImportId { get; set; }
        public string Operation { get; set; }
        public string Result { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Notes { get; set; }
    
        public virtual ImportLog ImportLog { get; set; }
    }
}
