//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informa.Models.DealsCompaniesDrugs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DCDContext : DbContext
    {
        public DCDContext()
            : base("name=dcd")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyRecordImportLog> CompanyRecordImportLogs { get; set; }
        public virtual DbSet<DealRecordImportLog> DealRecordImportLogs { get; set; }
        public virtual DbSet<Deal> Deals { get; set; }
        public virtual DbSet<DrugRecordImportLog> DrugRecordImportLogs { get; set; }
        public virtual DbSet<Drug> Drugs { get; set; }
        public virtual DbSet<ImportLog> ImportLogs { get; set; }
        public virtual DbSet<RelatedCompany> RelatedCompanies { get; set; }
    }
}
