//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informa.Models.DealsCompaniesDrugs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int RecordId { get; set; }
        public string RecordNumber { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastModified { get; set; }
        public string Title { get; set; }
    }
}
