//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informa.Models.DealsCompaniesDrugs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImportLog()
        {
            this.CompanyRecordImportLogs = new HashSet<CompanyRecordImportLog>();
            this.DealRecordImportLogs = new HashSet<DealRecordImportLog>();
            this.DrugRecordImportLogs = new HashSet<DrugRecordImportLog>();
        }
    
        public int Id { get; set; }
        public System.DateTime ImportStart { get; set; }
        public System.DateTime ImportEnd { get; set; }
        public string FileName { get; set; }
        public string Result { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyRecordImportLog> CompanyRecordImportLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealRecordImportLog> DealRecordImportLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugRecordImportLog> DrugRecordImportLogs { get; set; }
    }
}
