//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informa.Models.DealsCompaniesDrugs
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedCompany
    {
        public int Id { get; set; }
        public int CompanyRecordId { get; set; }
        public string RelatedCompanyRecordNumber { get; set; }
        public string RelatedCompanyPath { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
