using System.Collections.Generic;
using Sitecore.Data.Items;

namespace Sitecore.SharedSource.DataImporter.Mappings.Fields.Clinica
{
	public class FromTreatableConditionToDeviceMarketAreas : ToInformaDeviceMarketArea
	{
		public FromTreatableConditionToDeviceMarketAreas(Item i) : base(i)
		{
		}

		public override Dictionary<string, string> GetMapping()
		{
			Dictionary<string, string> d = new Dictionary<string, string>();

			d.Add("abnormal uterine bleeding", "");
			d.Add("abortion", "");
			d.Add("acidosis", "");
			d.Add("acne", "");
			d.Add("acromegaly", "");
			d.Add("acute coronary syndrome", "Blood Disorders");
			d.Add("acute lymphocytic leukaemia", "");
			d.Add("acute myelogenous leukaemia", "");
			d.Add("addison's disease", "");
			d.Add("adenosine deaminase deficiency", "");
			d.Add("adenovirus", "");
			d.Add("adhesive capsulitis", "");
			d.Add("adrenal cancer", "");
			d.Add("adrenoleukodystrophy", "");
			d.Add("african trypanosomiasis", "");
			d.Add("age-related macular degeneration", "Blood Disorders");
			d.Add("allergic rhinitis", "");
			d.Add("allergy", "Cancer");
			d.Add("alopecia", "");
			d.Add("alzheimer's disease", "Cancer");
			d.Add("amyloidosis", "");
			d.Add("amyotrophic lateral sclerosis", "");
			d.Add("anaemia", "Cancer");
			d.Add("anaesthesia", "Cancer");
			d.Add("anal fistula", "");
			d.Add("anaphylaxis", "");
			d.Add("aneurysm", "Cancer");
			d.Add("angina", "Cancer");
			d.Add("ankylosing spondylitis", "");
			d.Add("anorexia", "");
			d.Add("anthrax", "");
			d.Add("anxiety", "Cancer");
			d.Add("apnoea", "Cancer");
			d.Add("appendicitis", "");
			d.Add("arrhythmia", "Cancer");
			d.Add("arterial thrombosis", "");
			d.Add("arthritis", "Cancer");
			d.Add("aspergillus", "");
			d.Add("asthma", "Cancer");
			d.Add("atherosclerosis", "Cancer");
			d.Add("atopic eczema", "");
			d.Add("atrial fibrillation", "Cancer");
			d.Add("atrial tachycardia", "");
			d.Add("attention deficit hyperactivity disorder", "Cancer");
			d.Add("autism", "");
			d.Add("barrett's oesophagus", "");
			d.Add("basal cell cancer", "");
			d.Add("b-cell lymphoma", "");
			d.Add("benign prostatic hyperplasia", "Cancer");
			d.Add("biliary cancer", "");
			d.Add("biliary cirrhosis", "");
			d.Add("bladder cancer", "Cancer");
			d.Add("blepharitis", "");
			d.Add("blepharospasm", "");
			d.Add("bone cancer", "");
			d.Add("bone infection", "");
			d.Add("bone regeneration", "");
			d.Add("bowel incontinence", "");
			d.Add("bradycardia", "");
			d.Add("brain cancer", "");
			d.Add("brain inflammation", "");
			d.Add("breast cancer", "Cardiology");
			d.Add("bronchiectasis", "");
			d.Add("bronchitis", "");
			d.Add("brucella", "");
			d.Add("bulimia", "");
			d.Add("burns", "Cardiology::Neurology");
			d.Add("cachexia", "");
			d.Add("campylobacter", "");
			d.Add("cancer", "Cardiology");
			d.Add("cancer pain", "");
			d.Add("candida", "");
			d.Add("candida albicans", "");
			d.Add("carcinoid", "");
			d.Add("cardiac injury", "");
			d.Add("cartilage regeneration", "");
			d.Add("cataract", "Cardiology");
			d.Add("cerebral haemorrhage", "");
			d.Add("cerebral infarction", "");
			d.Add("cerebral ischaemia", "");
			d.Add("cervical cancer", "Cardiology");
			d.Add("cervical dysplasia", "");
			d.Add("chlamydia", "Cardiology");
			d.Add("cholera", "");
			d.Add("chronic fatigue syndrome", "");
			d.Add("chronic granulomatous disease", "");
			d.Add("chronic lymphocytic leukaemia", "");
			d.Add("chronic myelogenous leukaemia", "");
			d.Add("chronic obstructive pulmonary disease", "Cardiology");
			d.Add("clostridium", "Cardiology");
			d.Add("clostridium difficile", "");
			d.Add("cluster headache", "");
			d.Add("cns cancer", "");
			d.Add("cocaine addiction", "");
			d.Add("coeliac disease", "");
			d.Add("cognitive disorder", "Cardiology");
			d.Add("colitis", "");
			d.Add("colorectal cancer", "Cardiology");
			d.Add("complex regional pain", "Cardiology");
			d.Add("congenital adrenal hyperplasia", "");
			d.Add("conjunctivitis", "");
			d.Add("constipation", "");
			d.Add("corneal injury", "");
			d.Add("coronary artery bypass grafting", "");
			d.Add("coronary thrombosis", "");
			d.Add("coronavirus", "");
			d.Add("cough", "");
			d.Add("coxsackievirus", "");
			d.Add("creutzfeldt-jakob disease", "Cardiology");
			d.Add("crohn's disease", "");
			d.Add("croup", "");
			d.Add("cystic fibrosis", "Cardiology");
			d.Add("cytomegalovirus", "");
			d.Add("decubitus ulcer", "");
			d.Add("dengue virus", "");
			d.Add("depression", "Cardiology");
			d.Add("diabetes", "Cardiology");
			d.Add("diabetic nephropathy", "");
			d.Add("diabetic neuropathy", "");
			d.Add("diabetic retinopathy", "");
			d.Add("diabetic ulcer", "");
			d.Add("diagnostic", "Cardiology");
			d.Add("diarrhoea", "");
			d.Add("dilated cardiomyopathy", "");
			d.Add("diphtheria", "");
			d.Add("disseminated intravascular coagulation", "");
			d.Add("diverticulitis", "");
			d.Add("down's syndrome", "Cellular & Genetic");
			d.Add("drug addiction", "");
			d.Add("duodenal ulcer", "");
			d.Add("dupuytren's disease", "");
			d.Add("dwarfism", "");
			d.Add("dyskinesia", "");
			d.Add("dyspareunia", "");
			d.Add("dyspepsia", "");
			d.Add("dysplasia", "");
			d.Add("dystonia", "");
			d.Add("ebola virus", "");
			d.Add("eczema", "");
			d.Add("emphysema", "Dermatology");
			d.Add("endometrial cancer", "");
			d.Add("endometriosis", "");
			d.Add("enterovirus 71", "");
			d.Add("enuresis", "");
			d.Add("epidermolysis bullosa", "");
			d.Add("epilepsy", "Dermatology");
			d.Add("epstein-barr virus", "");
			d.Add("escherichia coli", "");
			d.Add("ewing's sarcoma", "");
			d.Add("fat malabsorption", "");
			d.Add("female contraception", "");
			d.Add("female infertility", "");
			d.Add("female sexual dysfunction", "");
			d.Add("fever", "");
			d.Add("fibromyalgia", "");
			d.Add("fibrosis", "Diabetic Care::Metabolic");
			d.Add("filariasis", "");
			d.Add("food allergy", "");
			d.Add("fragile x syndrome", "");
			d.Add("friedreich's ataxia", "");
			d.Add("fungal infection", "");
			d.Add("gastric ulcer", "");
			d.Add("gastritis", "");
			d.Add("gastroenteritis", "");
			d.Add("gastrointestinal cancer", "");
			d.Add("gastro-oesophageal reflux", "");
			d.Add("gastroparesis", "");
			d.Add("gaucher's disease", "");
			d.Add("giardia infection", "");
			d.Add("glaucoma", "Gastroenterology");
			d.Add("glomerulonephritis", "");
			d.Add("gonorrhoea", "Gynecology & Urology");
			d.Add("growth hormone deficiency", "");
			d.Add("haemochromatosis", "");
			d.Add("haemolytic anaemia", "");
			d.Add("haemolytic uraemic syndrome", "");
			d.Add("haemophilia", "");
			d.Add("haemophilia a", "");
			d.Add("haemophilus influenzae", "");
			d.Add("haemorrhage", "Gynecology & Urology");
			d.Add("haemorrhagic fever", "");
			d.Add("hairy cell leukaemia", "");
			d.Add("head and neck cancer", "");
			d.Add("head trauma", "");
			d.Add("headache", "Gynecology & Urology");
			d.Add("hearing loss", "");
			d.Add("heart failure", "Gynecology & Urology");
			d.Add("helicobacter pylori", "Gynecology & Urology");
			d.Add("hepatic dysfunction", "");
			d.Add("hepatic encephalopathy", "");
			d.Add("hepatitis virus", "");
			d.Add("hepatitis-b", "");
			d.Add("hepatitis-b virus", "");
			d.Add("hepatitis-c", "");
			d.Add("hereditary tyrosinaemia", "");
			d.Add("herpes", "Gynecology & Urology");
			d.Add("herpes simplex", "");
			d.Add("hiv", "Immunology");
			d.Add("hiv/aids", "Immunology");
			d.Add("homocystinuria", "");
			d.Add("hormone replacement therapy", "");
			d.Add("htlv", "");
			d.Add("human metapneumovirus", "");
			d.Add("human papilloma virus", "");
			d.Add("huntington's disease", "");
			d.Add("hyperbilirubinaemia", "");
			d.Add("hypercalcaemia", "");
			d.Add("hypercalcaemia of malignancy", "");
			d.Add("hypercholesterolaemia", "");
			d.Add("hyperlipidaemia", "");
			d.Add("hyperoxaluria", "");
			d.Add("hyperparathyroidism", "");
			d.Add("hyperphosphataemia", "");
			d.Add("hypertension", "In Vitro Diagnostics");
			d.Add("hyperthyroidism", "");
			d.Add("hyperuricaemia", "");
			d.Add("hypoglycaemia", "In Vitro Diagnostics");
			d.Add("hypogonadism", "");
			d.Add("hyponatraemia", "");
			d.Add("hypoparathyroidism", "");
			d.Add("hypotension", "");
			d.Add("hypothermia", "");
			d.Add("hypothyroidism", "");
			d.Add("idiopathic myelofibrosis", "");
			d.Add("ileus", "");
			d.Add("immunodeficiency", "");
			d.Add("impotence", "");
			d.Add("incontinence", "In Vitro Diagnostics");
			d.Add("induction", "");
			d.Add("infant respiratory distress syndrome", "");
			d.Add("infarction", "In Vitro Diagnostics::Gastroenterology");
			d.Add("inflammation", "In Vitro Diagnostics");
			d.Add("inflammatory bowel disease", "");
			d.Add("influenza", "In Vitro Diagnostics");
			d.Add("insomnia", "");
			d.Add("irritable bowel syndrome", "");
			d.Add("ischaemia", "In Vitro Diagnostics");
			d.Add("ischaemic cardiomyopathy", "");
			d.Add("japanese encephalitis", "");
			d.Add("jaundice", "");
			d.Add("kaposi's sarcoma", "");
			d.Add("keratoconus", "");
			d.Add("keratosis", "");
			d.Add("lassa virus", "");
			d.Add("lateral epicondylitis", "");
			d.Add("leber's congenital amaurosis", "");
			d.Add("leishmaniasis", "");
			d.Add("leprosy", "");
			d.Add("leukaemia", "In Vitro Diagnostics");
			d.Add("leukoplakia", "");
			d.Add("li-fraumeni syndrome", "");
			d.Add("lipodystrophy", "");
			d.Add("liposarcoma", "");
			d.Add("liver cancer", "In Vitro Diagnostics");
			d.Add("liver fibrosis", "");
			d.Add("long qt syndrome", "");
			d.Add("lower respiratory tract infection", "");
			d.Add("lung cancer", "In Vitro Diagnostics::Diagnostic Imaging");
			d.Add("lupus erythematosus", "");
			d.Add("lyme disease", "");
			d.Add("lymphoma", "In Vitro Diagnostics::Diagnostic Imaging");
			d.Add("macular oedema", "");
			d.Add("major depressive disorder", "");
			d.Add("malaria", "Metabolic::Cardiology");
			d.Add("male infertility", "");
			d.Add("marburg virus", "");
			d.Add("measles", "");
			d.Add("melanoma", "Metabolic");
			d.Add("meniere's disease", "");
			d.Add("meningitis", "");
			d.Add("menopausal symptoms", "");
			d.Add("menorrhagia", "");
			d.Add("menstrual disorder", "");
			d.Add("mental retardation", "");
			d.Add("mesothelioma", "");
			d.Add("metachromatic leukodystrophy", "");
			d.Add("migraine", "Metabolic");
			d.Add("miscarriage", "");
			d.Add("mitochondrial disease", "");
			d.Add("motor neurone disease", "");
			d.Add("mrsa", "Metabolic::Diabetic Care");
			d.Add("mssa", "");
			d.Add("mucositis", "");
			d.Add("multiple sclerosis", "n/a");
			d.Add("mumps", "");
			d.Add("muscle spasm", "");
			d.Add("muscular atrophy", "");
			d.Add("muscular dystrophy", "");
			d.Add("musculoskeletal infection", "");
			d.Add("musculoskeletal pain", "");
			d.Add("myasthenia gravis", "");
			d.Add("mycobacterium avium complex", "");
			d.Add("mycobacterium ulcerans", "");
			d.Add("myelodysplastic syndrome", "");
			d.Add("myeloma", "");
			d.Add("myocardial infarction", "Neurology");
			d.Add("myocarditis", "");
			d.Add("myopia", "Neurology");
			d.Add("narcolepsy", "");
			d.Add("nasopharyngeal cancer", "");
			d.Add("nausea and vomiting", "");
			d.Add("neisseria meningitidis", "");
			d.Add("nephritis", "");
			d.Add("nephropathy", "");
			d.Add("nerve injury", "");
			d.Add("neuroblastoma", "");
			d.Add("neurofibromatosis", "");
			d.Add("neuropathic pain", "");
			d.Add("neuropathy", "");
			d.Add("neutropenia", "");
			d.Add("nicotine addiction", "");
			d.Add("non-hodgkin's lymphoma", "");
			d.Add("non-small cell lung cancer", "Neurology");
			d.Add("norwalk virus", "");
			d.Add("nutrition", "Neurology");
			d.Add("obesity", "Neurology");
			d.Add("obsessive-compulsive disorder", "");
			d.Add("ocular inflammation", "");
			d.Add("oedema", "");
			d.Add("oesophageal cancer", "");
			d.Add("oesophagitis", "");
			d.Add("onchocerciasis", "");
			d.Add("onychomycosis", "");
			d.Add("oral cancer", "");
			d.Add("organophosphate poisoning", "");
			d.Add("osteoarthritis", "Neurology");
			d.Add("osteodystrophy", "");
			d.Add("osteomalacia", "");
			d.Add("osteonecrosis", "");
			d.Add("osteoporosis", "Neurology");
			d.Add("osteosarcoma", "");
			d.Add("otitis", "");
			d.Add("ovarian cancer", "Neurology");
			d.Add("overactive bladder", "Neurology");
			d.Add("paget's disease", "");
			d.Add("pain", "Neurology");
			d.Add("pancreatic cancer", "Neurology::Immunology");
			d.Add("pancreatic insufficiency", "");
			d.Add("pancreatitis", "");
			d.Add("panic disorder", "");
			d.Add("parainfluenza virus", "");
			d.Add("parkinson's disease", "Neurology");
			d.Add("partial epilepsy", "");
			d.Add("parvovirus", "");
			d.Add("patent ductus arteriosus", "");
			d.Add("pemphigus", "");
			d.Add("periodontitis", "");
			d.Add("peripheral vascular disease", "Neurology");
			d.Add("peyronie's disease", "");
			d.Add("phobia", "");
			d.Add("photodamage", "");
			d.Add("plasma substitute", "");
			d.Add("poisoning", "");
			d.Add("polio", "");
			d.Add("polycythaemia vera", "");
			d.Add("portal hypertension", "");
			d.Add("post-operative pain", "");
			d.Add("post-polio syndrome", "");
			d.Add("post-traumatic stress disorder", "Neurology");
			d.Add("prader-willi syndrome", "");
			d.Add("pre-eclampsia", "");
			d.Add("premature ejaculation", "");
			d.Add("preterm labour", "");
			d.Add("progressive multifocal leukoencephalopathy", "");
			d.Add("prostate cancer", "Neurology");
			d.Add("prostate inflammation", "Ophthalmology");
			d.Add("proteinuria", "");
			d.Add("pruritus", "");
			d.Add("psoriasis", "Ophthalmology::Surgery");
			d.Add("psoriatic arthritis", "");
			d.Add("psychosis", "");
			d.Add("pulmonary fibrosis", "");
			d.Add("pulmonary hypertension", "");
			d.Add("rabies", "");
			d.Add("radiation poisoning", "");
			d.Add("regeneration", "Ophthalmology");
			d.Add("relapsing-remitting multiple sclerosis", "");
			d.Add("renal cancer", "");
			d.Add("renal failure", "Ophthalmology");
			d.Add("renal injury", "");
			d.Add("reperfusion injury", "");
			d.Add("respiratory depression", "");
			d.Add("respiratory disease", "");
			d.Add("respiratory distress syndrome", "");
			d.Add("respiratory syncytial virus", "");
			d.Add("respiratory tract infection", "");
			d.Add("restenosis", "Ophthalmology");
			d.Add("restless legs syndrome", "");
			d.Add("retinal detachment", "");
			d.Add("retinal vein occlusion", "");
			d.Add("retinitis", "Ophthalmology");
			d.Add("retinopathy", "Orthopedics");
			d.Add("rheumatoid arthritis", "Orthopedics");
			d.Add("rhinitis", "");
			d.Add("rhinovirus", "");
			d.Add("rickets", "");
			d.Add("rickettsia", "");
			d.Add("rosacea", "");
			d.Add("rotavirus", "");
			d.Add("rubella", "");
			d.Add("salmonella", "");
			d.Add("sarcoidosis", "");
			d.Add("sarcoma", "");
			d.Add("sarcopenia", "");
			d.Add("scabies", "");
			d.Add("schistosomiasis", "");
			d.Add("schizophrenia", "");
			d.Add("scleroderma", "");
			d.Add("senile dementia", "");
			d.Add("sepsis", "Orthopedics");
			d.Add("severe combined immunodeficiency", "");
			d.Add("shigella", "");
			d.Add("sickle cell anaemia", "");
			d.Add("sinusitis", "");
			d.Add("sjogren's syndrome", "");
			d.Add("skin cancer", "Regenerative Medicine");
			d.Add("skin disorder", "");
			d.Add("skin infection", "");
			d.Add("small cell lung cancer", "Respiratory");
			d.Add("smallpox", "");
			d.Add("soft tissue sarcoma", "");
			d.Add("spinal cord injury", "Respiratory");
			d.Add("spinal muscular atrophy", "");
			d.Add("spinocerebellar ataxia", "");
			d.Add("squamous cell cancer", "");
			d.Add("staphylococcal", "");
			d.Add("std", "");
			d.Add("steatohepatitis", "");
			d.Add("stomach cancer", "");
			d.Add("stomatitis", "");
			d.Add("strabismus", "");
			d.Add("streptococcal", "");
			d.Add("subarachnoid haemorrhage", "");
			d.Add("supraventricular tachycardia", "");
			d.Add("synovial sarcoma", "");
			d.Add("systemic inflammatory response syndrome", "");
			d.Add("tachycardia", "Respiratory");
			d.Add("tendinitis", "");
			d.Add("testicular cancer", "");
			d.Add("tetanus", "");
			d.Add("thalassaemia", "");
			d.Add("thrombocythaemia", "");
			d.Add("thrombocytopenia", "");
			d.Add("thrombocytopenic purpura", "");
			d.Add("thrombocytosis", "");
			d.Add("thrombophlebitis", "");
			d.Add("thrombosis", "Respiratory");
			d.Add("thyroid cancer", "");
			d.Add("tick-borne encephalitis", "");
			d.Add("tinnitus", "");
			d.Add("tonsillitis", "");
			d.Add("toxoplasmosis", "");
			d.Add("transplant rejection", "");
			d.Add("transverse myelitis", "");
			d.Add("trichomoniasis", "");
			d.Add("trypanosomiasis", "");
			d.Add("tuberculosis", "Respiratory");
			d.Add("turner's syndrome", "");
			d.Add("type i diabetes", "Respiratory::Cellular & Genetic");
			d.Add("type ii diabetes", "");
			d.Add("typhoid", "");
			d.Add("ulcer", "Safety");
			d.Add("ulcerative colitis", "");
			d.Add("unstable angina", "");
			d.Add("urinary calculus", "");
			d.Add("urinary incontinence", "Wound Management");
			d.Add("urinary retention", "");
			d.Add("urinary tract infection", "");
			d.Add("urticaria", "");
			d.Add("uveitis", "");
			d.Add("vaginitis", "");
			d.Add("varicella zoster virus", "");
			d.Add("vascular dementia", "");
			d.Add("vascular endothelial dysfunction", "");
			d.Add("vasospasm", "");
			d.Add("venous insufficiency", "");
			d.Add("venous thrombosis", "");
			d.Add("ventricular fibrillation", "");
			d.Add("ventricular tachycardia", "");
			d.Add("vertigo", "");
			d.Add("vesicoureteral reflux", "");
			d.Add("vitamin d deficiency", "");
			d.Add("vitiligo", "Wound Management::In Vitro Diagnostics::Blood Disorders");
			d.Add("von willebrand's disease", "");
			d.Add("wolff-parkinson-white syndrome", "");
			d.Add("wound", "Wound Management");
			d.Add("xerostomia", "");
			d.Add("yellow fever", "");
			d.Add("yersinia pestis", "");

			return d;
		}
	}
}