//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformaSitecoreWord.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InformaSitecoreWord.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowdown {
            get {
                object obj = ResourceManager.GetObject("arrowdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowup {
            get {
                object obj = ResourceManager.GetObject("arrowup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap articleinfo_tabheader {
            get {
                object obj = ResourceManager.GetObject("articleinfo_tabheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap articlessidebars_browser {
            get {
                object obj = ResourceManager.GetObject("articlessidebars_browser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap asterisk {
            get {
                object obj = ResourceManager.GetObject("asterisk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap asteriskback {
            get {
                object obj = ResourceManager.GetObject("asteriskback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blankgreen {
            get {
                object obj = ResourceManager.GetObject("blankgreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blankred {
            get {
                object obj = ResourceManager.GetObject("blankred", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap broken_link {
            get {
                object obj = ResourceManager.GetObject("broken_link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closedfolder {
            get {
                object obj = ResourceManager.GetObject("closedfolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap companies_tabheader {
            get {
                object obj = ResourceManager.GetObject("companies_tabheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap company {
            get {
                object obj = ResourceManager.GetObject("company", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dealsdrugscompanies_browser {
            get {
                object obj = ResourceManager.GetObject("dealsdrugscompanies_browser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap downarrow {
            get {
                object obj = ResourceManager.GetObject("downarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExampleEmbed {
            get {
                object obj = ResourceManager.GetObject("ExampleEmbed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap generaltags_tabheader {
            get {
                object obj = ResourceManager.GetObject("generaltags_tabheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap geography_tabheader {
            get {
                object obj = ResourceManager.GetObject("geography_tabheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap graphics_tabheader {
            get {
                object obj = ResourceManager.GetObject("graphics_tabheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap greencheck {
            get {
                object obj = ResourceManager.GetObject("greencheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article not created.
        /// </summary>
        internal static string IFrameControl_Tableau_Article_Not_Created {
            get {
                return ResourceManager.GetString("IFrameControl_Tableau_Article_Not_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article needs to be created before inserting tableau component.
        /// </summary>
        internal static string IFrameControl_Tableau_Article_Required {
            get {
                return ResourceManager.GetString("IFrameControl_Tableau_Article_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau dashboard height is empty or not a number. Please provide valid dashboard height.
        /// </summary>
        internal static string IFrameControl_Tableau_DashBoardHeight_Required {
            get {
                return ResourceManager.GetString("IFrameControl_Tableau_DashBoardHeight_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau dashboard name is empty or invalid. Please provide valid dashboard name.
        /// </summary>
        internal static string IFrameControl_Tableau_DashBoardName_Required {
            get {
                return ResourceManager.GetString("IFrameControl_Tableau_DashBoardName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau dashboard width is empty or not a number. Please provide valid dashboard width.
        /// </summary>
        internal static string IFrameControl_Tableau_DashBoardWidth_Required {
            get {
                return ResourceManager.GetString("IFrameControl_Tableau_DashBoardWidth_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks the document is locked, doe you want to proceed data tool insertion.
        /// </summary>
        internal static string IFrameControl_Tableau_Document_Lock {
            get {
                return ResourceManager.GetString("IFrameControl_Tableau_Document_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word document is readonly.
        /// </summary>
        internal static string IFrameControl_Tableau_Document_Readonly {
            get {
                return ResourceManager.GetString("IFrameControl_Tableau_Document_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau dashboard page link label is empty or invalid. Please provide valid dashboard landing page link label.
        /// </summary>
        internal static string IFrameControl_Tableau_Page_Link_Label_Required {
            get {
                return ResourceManager.GetString("IFrameControl_Tableau_Page_Link_Label_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau dashboard page link is empty or invalid. Please provide valid dashboard landing page link.
        /// </summary>
        internal static string IFrameControl_Tableau_Page_Link_Required {
            get {
                return ResourceManager.GetString("IFrameControl_Tableau_Page_Link_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau dashboard page title is empty or invalid. Please provide valid dashboard title.
        /// </summary>
        internal static string IFrameControl_Tableau_Page_Title_Required {
            get {
                return ResourceManager.GetString("IFrameControl_Tableau_Page_Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login before inserting tableau.
        /// </summary>
        internal static string IFrameControl_Tableau_User_Not_LoggedIn {
            get {
                return ResourceManager.GetString("IFrameControl_Tableau_User_Not_LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is invalid or not permitted.
        ///Please make sure you have provided valid HTML with no script, style, or link tags..
        /// </summary>
        internal static string IFrameControl_uxInsertIFrame_Click_DesktopEmbedd {
            get {
                return ResourceManager.GetString("IFrameControl_uxInsertIFrame_Click_DesktopEmbedd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia content used is not secure. Please click on the Suggest Secure URL button to fix..
        /// </summary>
        internal static string IFrameControl_uxInsertIFrame_Click_Insecure_Multimedia {
            get {
                return ResourceManager.GetString("IFrameControl_uxInsertIFrame_Click_Insecure_Multimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia content is either missing, invalid or not secure. Please click &apos;OK&apos; to see instructions on how to correct this in red..
        /// </summary>
        internal static string IFrameControl_uxInsertIFrame_Click_Multimedia_Error {
            get {
                return ResourceManager.GetString("IFrameControl_uxInsertIFrame_Click_Multimedia_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imformaVideoPlaceholder2 {
            get {
                object obj = ResourceManager.GetObject("imformaVideoPlaceholder2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap industries_tabheader {
            get {
                object obj = ResourceManager.GetObject("industries_tabheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap link_32 {
            get {
                object obj = ResourceManager.GetObject("link-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap live {
            get {
                object obj = ResourceManager.GetObject("live", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lockedIcon {
            get {
                object obj = ResourceManager.GetObject("lockedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marketsegments_tabheader {
            get {
                object obj = ResourceManager.GetObject("marketsegments_tabheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap multimedia_etc_tabheader {
            get {
                object obj = ResourceManager.GetObject("multimedia_etc_tabheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap multimedia_etc_tabheader1 {
            get {
                object obj = ResourceManager.GetObject("multimedia_etc_tabheader1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap multimedia_tabheader {
            get {
                object obj = ResourceManager.GetObject("multimedia_tabheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notes_tabheader {
            get {
                object obj = ResourceManager.GetObject("notes_tabheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap openfolder {
            get {
                object obj = ResourceManager.GetObject("openfolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap orangebggradient {
            get {
                object obj = ResourceManager.GetObject("orangebggradient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap orangebggradientasterisk {
            get {
                object obj = ResourceManager.GetObject("orangebggradientasterisk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redx {
            get {
                object obj = ResourceManager.GetObject("redx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap relatedarticles_tabheader {
            get {
                object obj = ResourceManager.GetObject("relatedarticles_tabheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap relateddeals_tabheader {
            get {
                object obj = ResourceManager.GetObject("relateddeals_tabheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap selected {
            get {
                object obj = ResourceManager.GetObject("selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date not Set.
        /// </summary>
        internal static string SelectedRelatedArticles_CreateDateLabel_Date_not_Set {
            get {
                return ResourceManager.GetString("SelectedRelatedArticles_CreateDateLabel_Date_not_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sidearrow {
            get {
                object obj = ResourceManager.GetObject("sidearrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap splashlogo {
            get {
                object obj = ResourceManager.GetObject("splashlogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap subjects_tabheader {
            get {
                object obj = ResourceManager.GetObject("subjects_tabheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap summary_tabheader {
            get {
                object obj = ResourceManager.GetObject("summary_tabheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap supportingdocs_tabheader {
            get {
                object obj = ResourceManager.GetObject("supportingdocs_tabheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap supportingdocuments_browser {
            get {
                object obj = ResourceManager.GetObject("supportingdocuments_browser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid document.
        /// </summary>
        internal static string SupportingDocumentsControl_uxViewDocument_Click_Please_select_a_valid_document {
            get {
                return ResourceManager.GetString("SupportingDocumentsControl_uxViewDocument_Click_Please_select_a_valid_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TabHeaders_companies {
            get {
                object obj = ResourceManager.GetObject("TabHeaders_companies", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TabHeaders_deals {
            get {
                object obj = ResourceManager.GetObject("TabHeaders_deals", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TabHeaders_drugs {
            get {
                object obj = ResourceManager.GetObject("TabHeaders_drugs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TabHeaders_graphics {
            get {
                object obj = ResourceManager.GetObject("TabHeaders_graphics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TabHeaders_related_articles {
            get {
                object obj = ResourceManager.GetObject("TabHeaders_related_articles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TabHeaders_sidebars {
            get {
                object obj = ResourceManager.GetObject("TabHeaders_sidebars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap therapeutic_tabheader {
            get {
                object obj = ResourceManager.GetObject("therapeutic_tabheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree {
            get {
                object obj = ResourceManager.GetObject("tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unlockIcon {
            get {
                object obj = ResourceManager.GetObject("unlockIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
