USE [master]
GO

/****** Object:  Database [Informa_Custom]    Script Date: 3/15/2016 4:26:54 PM ******/
CREATE DATABASE [Informa_Custom]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Informa_Custom.mdf', FILENAME = N'D:\data\Informa_Custom.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Informa_Custom_log.ldf', FILENAME = N'D:\data\Informa_Custom_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Informa_Custom] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Informa_Custom].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Informa_Custom] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Informa_Custom] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Informa_Custom] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Informa_Custom] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Informa_Custom] SET ARITHABORT OFF 
GO

ALTER DATABASE [Informa_Custom] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Informa_Custom] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Informa_Custom] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Informa_Custom] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Informa_Custom] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Informa_Custom] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Informa_Custom] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Informa_Custom] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Informa_Custom] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Informa_Custom] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Informa_Custom] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Informa_Custom] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Informa_Custom] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Informa_Custom] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Informa_Custom] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Informa_Custom] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Informa_Custom] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Informa_Custom] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Informa_Custom] SET  MULTI_USER 
GO

ALTER DATABASE [Informa_Custom] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Informa_Custom] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Informa_Custom] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Informa_Custom] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Informa_Custom] SET  READ_WRITE 
GO

USE [Informa_Custom]
GO

CREATE TABLE [dbo].[ScheduledPublishes](
	[Id] [uniqueidentifier] NOT NULL,
	[Added] [datetime] NOT NULL,
	[LastUpdated] [datetime] NOT NULL,
	[ItemId] [uniqueidentifier] NOT NULL,
	[Language] [nvarchar](max) NULL,
	[Version] [nvarchar](max) NULL,
	[PublishOn] [datetime] NOT NULL,
	[Published] [bit] NOT NULL,
	[Type] [int] NOT NULL,
 CONSTRAINT [PK_dbo.ScheduledPublishes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


